serverrp/glavarp/urls.py
from django.urls import path
from glavarp.views import(
    main_page , post_page , projectstest , docwith  ,adminmain , 
    operplans ,migratio_to_br, operplan , cotrudniki , compani , presaiall
)
app_name='glavarp'
# {% url 'glavarp:cotrudniki' %}
urlpatterns = [
    path('g', main_page, name='main'),
    path('j/',post_page, name='post'),
    path('creatrnew/',docwith, name='doc'),
    path('operplan/',operplans, name='op'),
    path('migr/',migratio_to_br, name='mig'),
    path('',adminmain, name='admins'),
    path('qff/<int:pk>/',operplan, name='oper'),
    path('cotrudniki/',cotrudniki, name='cotrudniki'),
    path('presaiall/',presaiall, name='presaiall'),
    path('compani/',compani, name='compani'),

    path('q/',projectstest, name='proj')
]

serverrp/post/urls.py
from django.urls import path , include
from post.views import post_page ,post_page_generate , post_page_name , post_dowlend


app_name='post'

urlpatterns = [
    path('', post_page, name='postpage'), 
    path('<str:pk>/', post_page_generate, name='postpagegenerate'), 
    path('name/<str:pk>/', post_page_name, name='postname'), 
    path('file/<str:pk>/', post_dowlend, name='pismofile'), 
]

serverrp/preseil/urls.py
from django.urls import path , include
from preseil.views import (
    preseilmain , preseilmainall , preseilmainmy ,preseilnew ,presailotchet
)
app_name='preseil'

urlpatterns = [
    path('<int:pk>/', preseilmain, name='preselproj'), 
    path('', preseilmainmy, name='presailall'), 
    path('all/', preseilmainall, name='presail'), 
    path('new/', preseilnew, name='presailnew'), 
    path('otch/', presailotchet, name='presailotchet'), 
]

serverrp/projects/urls.py
from django.urls import path , include
from projects.views import(
    projects_views , projects_detail, otchet , logout_view, logins , projects_detail_st_low , list_otch ,dashboard_allprod,
    projects_views_all, dashbotrd_pass, dashboard_pasport , dashboard_myprod ,dashboard_operplan ,
    pmo_main_page ,pmo_post_page,  deshbord_prodj,  pasport_red,
    check , dashbord_pocaz , otchet_new , del_sotr_from
)

app_name='projects'

urlpatterns = [
    path('', projects_views, name='views'), # все проекты / Мои проекты (отчеты)
    path('<int:pk>/',projects_detail,name='detail'), # отче проекта
    path('otch/',otchet,name='otch'),#  отчет для М
    path('otch2/',otchet_new,name='otchetnew'),#  отчет для М 2
    path('logout/',logout_view ,name='logout'),# Выйти
    path('lg/', logins ,name='ligin'),# Войти 
    path('st/<int:pk>/', projects_detail_st_low,name='detail_st'),# Отчет проекта- Степанова
    path('ch/', check , name='chrck'),# Проверка обновления Обновить код 
    path('pmomaim/',pmo_main_page, name="pmo"),# PMO
    path('pmopost/',pmo_post_page, name="pmopost"),#  РМО paccылка
    path('allprod/' ,dashboard_allprod , name="allprod"),# Все проекты (Пас)
    path('myprod/' ,dashboard_myprod , name="myprod"),# Мои проекты (Пас)
    path('proect/<int:pk>/' ,dashboard_pasport , name="passs"),# Паспорт проекта 
    path('operplam/<int:pk>/',dashboard_operplan, name="operplan"),# Обновить говно полное  
    path('dashboard/' , deshbord_prodj , name="dashbord"),# Доработаь 
    path('ot/', list_otch ,name='list'),# Общий отчет с возможностью менять (Перписать)
    path('all/', projects_views_all , name='all'),#Все проекты  (отчеты)
    path('otshetpass/',dashbotrd_pass, name='dashpass' ), # Отчет таблица общий без сылок 
    path('pasportre/<int:pk>/',pasport_red, name="pasportre"), # редактировать информацию по проекту 

    path('del/<int:pk>/<str:cot>/', del_sotr_from , name='del_sort_form'  ), # Удалить сотрудкника 

    path('pok/<int:pk>/',dashbord_pocaz, name="pok"),# удалить нахер 
    #path('test/', projects_views2 , name='views2'),# ТеСТ
    #path('creat/',crete_prodjects, name='create'),# удалить нахер 
    #path('proect/', projects_moiproecs, name='moipr'),# Удалить не актуально
    #path('mig/', from_exel_to_sql),#удалить нахер 
    #path('pasport/<int:pk>/',dashbord_pocaz, name="pasport"),# удалить нахер 
    #path('pasport/ch/<int:pk>', pr_pasport_red, name="pasportred"),#удалить нахер 
    #path('zadatha/',zadatha, name = "zadatha" ),#удалить нахер 
    #path('zadath/<int:pk>' , zadaniadetail , name="zadditail"),#удалить нахер 
    #path('zadathamoi/',zadathamoi, name = "zadathamoi"),#удалить нахер 
    #path('zadathvse/<int:pk>' ,zadathavse , name="zadathavse"),#удалить нахер 
    #path('create/',   dashboard_create, name='creates') # Надо доделать, а лучше перенести в другой модуль 
]

serverrp/resurses/urls.py
from django.urls import path
from resurses.views import(
    main ,contacts , mycontacts , mycontactcreate, myplans , 
    myworkers , mywokrcrete ,myworcersall ,mywokrcrename , mcontactdetail ,allcompanis , resorsmatc_all
    ,myotdel , allresorses , resorsmatch , rezalt , otdelcontacts , companicontacts , allcontactscompani, 
    otdelcontacts_all , soglosovanie_resursu , makemigratinonresors , prog
)
app_name='resurses'

urlpatterns = [
    path('g', main, name='main'),
    path('contacts/', contacts, name='contacts'),
    path('mycont/<int:pk>/' , mycontacts, name = 'myconts'),
    path('plans/', myplans , name='myplans'),
    path('mycontcr/<int:pk>/' , mycontactcreate, name ='mycontscr'),
    path('workers/<int:pk>/' , myworkers , name="myworkers" ),
    path('rename/<str:pk>/' , mywokrcrename , name="mywokrcrename" ),
    path('myworcersall/', myworcersall , name='myworcersall'),
    path('mywokrcrete/', mywokrcrete , name='mywokrcrete'),
    path('myotdel/<int:pk>/' , myotdel , name="myotdel" ),
    path('otdelcontacts/<int:pk>/' , otdelcontacts , name="otdelcontacts" ),
    path('allresorses/', allresorses , name='allresorses'),
    path('resorsmatch/', resorsmatch , name='resorsmatch'),
    path('rezalt/<int:pk>/', rezalt , name='rezalt'),
    path('companicontacts/<int:pk>/', companicontacts , name='companicontacts'),
    path('allcontactscompani/', allcontactscompani , name='allcontactscompani'),
    path('allcompanis/', allcompanis , name='allcompanis'),
    path('cont/<str:pk>/',mcontactdetail, name='contactsname'),
    path('resorsmatcofall/', resorsmatc_all , name='resorsmatcofall'),
    path('allotd/<str:pk>/',otdelcontacts_all, name='allotd'),
    path('soglos/', soglosovanie_resursu , name = 'soglosov'),
    path('mig/<str:pk>/', makemigratinonresors),
    path('d/', prog ),
]

#

serverrp/serverrp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projects.urls')),
    path('ad/',include('glavarp.urls')),
    path('a/',include('resurses.urls')),
    path('p/',include('post.urls')),
    path('preseil/',include('preseil.urls')),
    path('plan/',include('resorsplaning.urls')),
    path('ut/',include('ushetvremeni.urls')),
    path('b/',include('bazaznaniy.urls')),
    
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

serverrp/serverrp/templates/basic.html
{% extends 'index.html' %}

<!-- титул  -->
{% block page_title %}

{% load static %}

{% endblock %}

<!-- Стили -->
{% block page_styles %}

{% endblock %}

<!-- Слайдер -->
{% block page_slader %}

{% endblock %}

<!-- Основной контент -->
{% block page_contecst %}

{% endblock %}

serverrp/serverrp/templates/index.html
<!DOCTYPE html>
{% load static %}
{% load resors %}
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Makeev Max">
    <link rel="icon"  href="{% static "projects/pmo.png" %}" >



	{% block page_title %}
    {% endblock %}
	
	{% block page_styles %}
    {% endblock %}
    
	<!-- Bootstrap 4.0-->
	<link rel="stylesheet"  href="{% static "projects/assets/vendor_components/bootstrap/dist/css/bootstrap.css" %}" type="text/css">
	
	<!-- Bootstrap extend-->
	<link rel="stylesheet" href="{% static "projects/css/bootstrap-extend.css" %}" type="text/css" >
	
	<!-- theme style -->
	<link rel="stylesheet" href="{% static "projects/css/master_style.css" %}" type="text/css">
	
	<!-- Materiel Admin skins -->
	<link rel="stylesheet" href="{% static "projects/css/skins/_all-skins.css" %}" type="text/css">

  </head>

<body class="hold-transition skin-black sidebar-mini">
<div class="wrapper">

  <header class="main-header">	  	
  	<!-- Sidebar toggle button-->
	  <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
		<span class="sr-only">Navigation</span>
	  </a>
    <!-- Logo -->
    <a href="{% url 'projects:dashbord' %}" class="logo">
      <!-- mini logo -->
	  
      <!-- logo-->
      <span class="logo-lg">
		  <img src="{% static "projects/images/gal1.png" %}"  alt="logo" class="light-logo">
	  	  <img src="{% static "projects/images/gal1.png" %}"  alt="logo" class="dark-logo">
	  </span>
    </a>
    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top">	  
	  <div class="ml-10 app-menu">
		<ul class="header-megamenu nav">
			<li class="btn-group nav-item">
				<a href="#" class="nav-link rounded" data-provide="fullscreen" title="Full Screen">
					<i class="mdi mdi-crop-free"></i>
				</a>
			</li>
			{% if user.is_staff %}	  
			<li class="btn-group nav-item">
				<a href="#" class="nav-link rounded" data-toggle="dropdown" aria-expanded="false">
					<i class="nav-link-icon mdi mdi-view-dashboard text-white mx-5"> </i>
					Меню
					<i class="fa fa-angle-down ml-2"></i>
				</a>
				<div class="dropdown-menu dropdown-grid">
					<div class="dropdown-mega-menu">
						<div class="row">
							<div class="col-lg-4 col-12">
								<ul class="nav flex-column">
									<li class="nav-item-header nav-item">
										Админ
									</li>
									<li class="nav-item">
										<a href="{% url 'projects:all' %}" class="nav-link">
											<i class="nav-link-icon fa fa-inbox">
											</i>
											<span>
												Отчеты 
											</span>
										</a>
									</li>
									<li class="nav-item"> 
											<a href="{% url 'projects:allprod' %}" class="nav-link ">
												<i class="nav-link-icon fa fa-dashboard">
												</i>
												<span>
													Паспорта
												</span>
											</a>
									</li>
									<li class="nav-item">
										<a href="{% url 'projects:pmo' %}" class="nav-link">
											<i class="nav-link-icon fa fa-book">
											</i>
											<span>
												РМО
											</span>
											
										</a>
									</li>
									<li class="nav-item">
										<a href="{% url 'projects:otchetnew' %}" class="nav-link">
											<i class="nav-link-icon fa fa-picture-o">
											</i>
											<span>
												Отчет
											</span>
										</a>
									</li>
									
								</ul>
							</div>
							<!-- -->
							<div class="col-lg-4 col-12 bx-1">
								<ul class="nav flex-column">
									<li class="nav-item-header nav-item">
										Управление ресурсами 
									</li>
									<li class="nav-item">
										<a href="{% url 'resurses:mywokrcrete' %}" class="nav-link">
											Добавить сотрудника 
										</a>
									</li>
									<li class="nav-item">
										<a href="{% url 'resurses:myworcersall' %}" class="nav-link">
											Все сотрудники 
										</a>
									</li>
									<li class="nav-item">
										<a href="{% url 'glavarp:cotrudniki' %}" class="nav-link"> Загрузить сотрудников </a>
									</li>
									<li class="nav-item">
										<a href="{% url 'resurses:resorsmatcofall' %}" class="nav-link">Ресурсы  </a>
									</li>
								</ul>
							</div>
							<div class="col-lg-4 col-12">
								<ul class="nav flex-column">
									<li class="nav-item-header nav-item">
										Настройки
									</li>
									<li class="nav-item">
										<a href="{% url 'glavarp:doc' %}" class="nav-link">Создать новый проект 
										</a>
									</li>
									<li class="nav-item">
										<a href="#" class="nav-link"> Добавить контакт
										</a>
									</li>
									<li class="nav-item">
										<a href="{% url 'projects:dashpass' %}" class="nav-link">Отчет общий
											
										</a>
									</li>
									<li class="nav-item">
										<a href="{% url 'glavarp:admins' %}" class="nav-link">Админ панель.
										</a>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</li>
			{% endif %}
			
		</ul> 
	  </div>
		
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
		  
		  <li class="search-box">
            <a class="nav-link hidden-sm-down" href="#"><i class="ion ion-person"></i> {{ user.first_name }} </a>
            
		  </li>	
		  
		  <!-- User Account-->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="{% static "projects/images/user5-128x128.jpg" %}"  class="user-image rounded-circle b-2" alt="User Image">
            </a>
            <ul class="dropdown-menu scale-up">
              <!-- Menu Body -->
              <li class="user-body bt-0">
                <div class="row no-gutters">
                  <div class="col-12 text-left">
                    <a href="#"><i class="ion ion-person"></i> Профиль</a>
                  </div>
				  
				<div role="separator" class="divider col-12"></div>
				  <div class="col-12 text-left">
						{% if user.is_authenticated %}
						<a href= "{% url 'projects:logout' %}"> <i class="fa fa-power-off"></i>Выйти</a>
						{% endif %}
						{% if user.is_anonymous  %}
						<a href= "{% url 'projects:ligin' %}"> <i class="fa fa-power-off"></i>Войти</a>
						{% endif %}
					
                  </div>				
                </div>
                <!-- /.row -->
              </li>
            </ul>
          </li>	  
      
		
        </ul>
      </div>
    </nav>
  </header>
  
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar-->
    <section class="sidebar">
      
      <!-- sidebar menu-->
      <ul class="sidebar-menu" data-widget="tree">
		  
        <li>
          <a href="{% url 'projects:dashbord' %}" hidden>
            <i class="ti-dashboard"></i> <span>Dashboard</span>
          </a>
        </li>				  

        <li class="header">Управление проектами</li>	
	  
		<li>
          <a href="{% url 'projects:myprod' %}">
            <i class="ti-comments"></i>
			<span>Проекты</span>
			{% if user.first_name|projcount != '0' %}
			  <span class="pull-right-container">
				<small class="label pull-right bg-warning">{{ user.first_name|projcount }}</small>
			  </span>
			  {% endif %}
          </a>
		</li>	
		<li>
			<a href="{% url 'preseil:presailall' %}">
			  <i class="ti-light-bulb"></i>
			  <span>Пресейл</span>
			  {% if user.username|presailcount != '0' %}
			  <span class="pull-right-container">
				<small class="label pull-right bg-warning">{{ user.username|presailcount }}</small>
			  </span>
			  {% endif %}
			</a>
		  </li>		  
		<li>
		<li>
		<a href="{% url 'projects:views' %}">
			<i class="ti-calendar"></i>
			<span> Статус  </span>
		</a>
		</li>		  
		
		  <li class="treeview">
			<a href="#">
			  <i class="ti-panel"></i> <span>Ресурсы</span>
			  <span class="pull-right-container">
				<i class="fa fa-caret-down pull-right"></i>
			  </span>
			</a>
			<ul class="treeview-menu" style="display: none;">
			  <li><a href="{% url 'resorsplaning:plani'%}">План</a></li> 
			  <li><a href="{% url 'resurses:allresorses'%}">Факт</a></li>
			  <li><a href="{% url 'ushetvremeni:vrem' pk=0 %}">Учет времени</a></li>
			</ul>
		  </li>  
		  <li class="treeview">
			<a href="#">
			  <i class="ti-id-badge"></i> <span>Контакты</span>
			  <span class="pull-right-container">
				<i class="fa fa-caret-down pull-right"></i>
			  </span>
			</a>
			<ul class="treeview-menu" style="display: none;">
			  <li><a href="{% url 'resurses:allcontactscompani'%}">Контакты</a></li>
			  <li><a href="{% url 'resurses:allcompanis'%}">Заказчики</a></li>
			  <li><a href="{% url 'resurses:myworcersall' %}"> Сотрудники</a> </li>
			</ul>
		  </li>
		  <!-- 
		  <li class="header">  </li>	
		  -->  
		  <li> 
			<a href="{% url 'resurses:myplans'%}">
			  <i class=" ti-clipboard"></i>
			  <span>Задачи</span>
			  {% if user.username|mailbox != '0' %}
			  <span class="pull-right-container">
				<small class="label pull-right bg-warning">{{ user.username|mailbox }}</small>
			  </span>
			  {% endif %}
			</a>
		  </li>	
		<li>
			<a href="{% url 'post:postpage'%}">
				  <i class="ti-email"></i>
				  <span>Письма</span>
			</a>
		</li>
		<li>
			<a href="{% url 'bazaznaniy:main'%}" >
				  <i class="ti-bookmark-alt"></i>
				  <span>База знаний</span>
			</a>
		</li>		  

		{% if user.is_staff %}	  
		<li class="header">Контроль </li>	
		<li>
          <a href="{% url 'projects:otchetnew' %}">
            <i class="ti-blackboard"></i>
			<span>Отчет</span>
          </a>
		</li>
		<li>
          <a href="{% url 'projects:pmo' %}">
            <i class=" ti-settings"></i>
			<span>РМО</span>
          </a>
		</li>
	
		{% endif %}		  		
		
		{% if user.is_authenticated %}  
		{% block page_slader %}
    	{% endblock %}
		{% endif %}
      </ul>
    </section>
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
	  
    <!-- Main content -->
    <section class="content">	
		<div class="container-full">
				{% block page_contecst_anon %}

				{% endblock %}

				{% if user.is_authenticated %}   	
				{% block page_contecst %}

				{% endblock %}
				{% endif %}
				{% if user.is_anonymous  %}
						<a href= "{% url 'projects:ligin' %}" class="btn btn-lg btn-primary btn-block">>Войти</a>
				{% endif %}
		</div>	  		      
	</section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <div class="pull-right d-none d-sm-inline-block">
        <ul class="nav nav-primary nav-dotted nav-dot-separated justify-content-center justify-content-md-end">
		  <li class="nav-item">
			<a href="mailto:makeev.m@galaktika.ru" class="nav-link" target="_blank">Поддержка</a>
		  </li>
		</ul>
    </div>
	<div class="col-lg-6">
			<div class="copyright text-center  text-lg-left  text-muted">
			  &copy; 2020 <a href="mailto:makeev.21@mail.ru" class="font-weight-bold ml-1" target="_blank">Макеев М.С. </a>
			</div>
		  </div>
  </footer>
</div>

  	
	
	<!-- jQuery 3 --> 
	<script src="{% static "projects/assets/vendor_components/jquery-3.3.1/jquery-3.3.1.js" %}" ></script>
	<!-- popper -->
	<script src="{% static "projects/assets/vendor_components/popper/dist/popper.min.js" %}" ></script>
	<!-- Bootstrap 4.1-->
	<script src="{% static "projects/assets/vendor_components/bootstrap/dist/js/bootstrap.js" %}" ></script>	
	<script src="{% static "projects/assets/vendor_components/jquery-slimscroll/jquery.slimscroll.js" %}" ></script>
	<!-- FastClick -->
	<script src="{% static "projects/assets/vendor_components/fastclick/lib/fastclick.js" %}" ></script>
	<!-- fullscreen -->
	<script src="{% static "projects/assets/vendor_components/screenfull/screenfull.js" %}" ></script>
	
	
    <script src="{% static "projects/assets/vendor_components/fusioncharts-suite-xt/js/fusioncharts.js" %}" ></script>
    <script src="{% static "projects/assets/vendor_components/fusioncharts-suite-xt/js/themes/fusioncharts.theme.fusion.js" %}" ></script>
	<script src="{% static "projects/assets/vendor_components/apexcharts-bundle/irregular-data-series.js" %}" ></script>
	<script src="{% static "projects/assets/vendor_components/apexcharts-bundle/dist/apexcharts.js" %}" ></script>
		
	<!-- Materiel Admin App -->
	<script src="{% static "projects/js/template.js" %}" ></script>

	{% block page_staticjsandcss %}
	{% endblock %}

	
</body>
</html>

serverrp/serverrp/templates/master.html
{% load static %}
<html>
<head>
    <meta charset="utf-8" />
    {% block page_title %}
    {% endblock %}
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link  href="{% static "projects/css/bootstrap.min.css" %}" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">    

    {% block page_styles %}
    {% endblock %}
    <!--
       <link rel="stylesheet" href="{% static 'projects/index.css' %}"> 
    -->
    <style>
          .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }}
            main > .container {
        padding: 60px 15px 0;
        }

        .footer {
        background-color: #f5f5f5;
        }

        .footer > .container {
        padding-right: 15px;
        padding-left: 15px;
        }

        code {
        font-size: 80%;
        }
    </style>
</head>
<body>

<header>
<!-- Fixed navbar -->
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="{% url 'projects:views' %}"><img src="{% static "projects/galaktika 1.png" %}" alt="" width="140" height="60"> </a>
     
    <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
        <a class="nav-link" href="{% url 'projects:views' %}">Все проекты <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'projects:moipr' %}">Мои проекты</a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'projects:ligin' %}" >Войти</a>
        </li>
        {% if user.is_staff %}
        <li class="nav-item">
        <a class="nav-link" href="{% url 'glavarp:main' %}" >PMO</a>
        </li>
        {% endif %}
    </ul>
    <form class="form-inline mt-2 mt-md-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Искать</button>
    </form>
    </div>
</nav>
</header>

<!-- Begin page content -->
<main role="main" class="flex-shrink-0">
<!--
<table width="160">
    <tr width="150">
        <td bgcolor="1A307E">
        <img src="{% static "projects/galaktika 1.png" %}" width="160" height="78" >
        </td>
    </tr>
    <tr>
        <td class="tab">
            {{ user.first_name }}
          <span class="col2">{{ user.email }} </span>  
        </td>
    </tr>
    <tr>
        <td class="tab">
            <a href="{% url 'projects:views' %}" > Все проекты </a>
            <a href="{% url 'projects:moipr' %}" > Мои проекты </a>
            <a href="{% url 'projects:otch' %}" > Отчет </a>
            <a href="{% url 'projects:ligin' %}" > Войти </a>

            {% if user.is_staff %}
            <a href="{% url 'glavarp:main' %}" > PMO </a>
            {% endif %}
        </td>
    </tr>
</table>
</div>
-->

        {% if user.is_authenticated %}
        
        {% block page_content %}
        {% endblock %}

        {% endif %}
</main>
    
</body>
</html>