serverrp/post/urls.py
from django.urls import path , include
from post.views import post_page ,post_page_generate , post_page_name , post_dowlend


app_name='post'

urlpatterns = [
    path('', post_page, name='postpage'), 
    path('<str:pk>/', post_page_generate, name='postpagegenerate'), 
    path('name/<str:pk>/', post_page_name, name='postname'), 
    path('file/<str:pk>/', post_dowlend, name='pismofile'), 
]

serverrp/preseil/urls.py
from django.urls import path , include
from preseil.views import (
    preseilmain , preseilmainall , preseilmainmy ,preseilnew ,presailotchet
)
app_name='preseil'

urlpatterns = [
    path('<int:pk>/', preseilmain, name='preselproj'), 
    path('', preseilmainmy, name='presailall'), 
    path('all/', preseilmainall, name='presail'), 
    path('new/', preseilnew, name='presailnew'), 
    path('otch/', presailotchet, name='presailotchet'), 
]

serverrp/projects/urls.py
from django.urls import path , include
from projects.views import(
    projects_views , projects_detail, otchet , logout_view, logins , projects_detail_st_low , list_otch ,dashboard_allprod,
    projects_views_all, dashbotrd_pass, dashboard_pasport , dashboard_myprod ,dashboard_operplan ,
    pmo_main_page ,pmo_post_page,  deshbord_prodj,  pasport_red,
    check , dashbord_pocaz , otchet_new , del_sotr_from
)

app_name='projects'

urlpatterns = [
    path('', projects_views, name='views'), # все проекты / Мои проекты (отчеты)
    path('<int:pk>/',projects_detail,name='detail'), # отче проекта
    path('otch/',otchet,name='otch'),#  отчет для М
    path('otch2/',otchet_new,name='otchetnew'),#  отчет для М 2
    path('logout/',logout_view ,name='logout'),# Выйти
    path('lg/', logins ,name='ligin'),# Войти 
    path('st/<int:pk>/', projects_detail_st_low,name='detail_st'),# Отчет проекта- Степанова
    path('ch/', check , name='chrck'),# Проверка обновления Обновить код 
    path('pmomaim/',pmo_main_page, name="pmo"),# PMO
    path('pmopost/',pmo_post_page, name="pmopost"),#  РМО paccылка
    path('allprod/' ,dashboard_allprod , name="allprod"),# Все проекты (Пас)
    path('myprod/' ,dashboard_myprod , name="myprod"),# Мои проекты (Пас)
    path('proect/<int:pk>/' ,dashboard_pasport , name="passs"),# Паспорт проекта 
    path('operplam/<int:pk>/',dashboard_operplan, name="operplan"),# Обновить говно полное  
    path('dashboard/' , deshbord_prodj , name="dashbord"),# Доработаь 
    path('ot/', list_otch ,name='list'),# Общий отчет с возможностью менять (Перписать)
    path('all/', projects_views_all , name='all'),#Все проекты  (отчеты)
    path('otshetpass/',dashbotrd_pass, name='dashpass' ), # Отчет таблица общий без сылок 
    path('pasportre/<int:pk>/',pasport_red, name="pasportre"), # редактировать информацию по проекту 

    path('del/<int:pk>/<str:cot>/', del_sotr_from , name='del_sort_form'  ), # Удалить сотрудкника 

    path('pok/<int:pk>/',dashbord_pocaz, name="pok"),# удалить нахер 
    #path('test/', projects_views2 , name='views2'),# ТеСТ
    #path('creat/',crete_prodjects, name='create'),# удалить нахер 
    #path('proect/', projects_moiproecs, name='moipr'),# Удалить не актуально
    #path('mig/', from_exel_to_sql),#удалить нахер 
    #path('pasport/<int:pk>/',dashbord_pocaz, name="pasport"),# удалить нахер 
    #path('pasport/ch/<int:pk>', pr_pasport_red, name="pasportred"),#удалить нахер 
    #path('zadatha/',zadatha, name = "zadatha" ),#удалить нахер 
    #path('zadath/<int:pk>' , zadaniadetail , name="zadditail"),#удалить нахер 
    #path('zadathamoi/',zadathamoi, name = "zadathamoi"),#удалить нахер 
    #path('zadathvse/<int:pk>' ,zadathavse , name="zadathavse"),#удалить нахер 
    #path('create/',   dashboard_create, name='creates') # Надо доделать, а лучше перенести в другой модуль 
]

serverrp/resurses/urls.py
from django.urls import path
from resurses.views import(
    main ,contacts , mycontacts , mycontactcreate, myplans , 
    myworkers , mywokrcrete ,myworcersall ,mywokrcrename , mcontactdetail ,allcompanis , resorsmatc_all
    ,myotdel , allresorses , resorsmatch , rezalt , otdelcontacts , companicontacts , allcontactscompani, 
    otdelcontacts_all , soglosovanie_resursu , makemigratinonresors , prog
)
app_name='resurses'

urlpatterns = [
    path('g', main, name='main'),
    path('contacts/', contacts, name='contacts'),
    path('mycont/<int:pk>/' , mycontacts, name = 'myconts'),
    path('plans/', myplans , name='myplans'),
    path('mycontcr/<int:pk>/' , mycontactcreate, name ='mycontscr'),
    path('workers/<int:pk>/' , myworkers , name="myworkers" ),
    path('rename/<str:pk>/' , mywokrcrename , name="mywokrcrename" ),
    path('myworcersall/', myworcersall , name='myworcersall'),
    path('mywokrcrete/', mywokrcrete , name='mywokrcrete'),
    path('myotdel/<int:pk>/' , myotdel , name="myotdel" ),
    path('otdelcontacts/<int:pk>/' , otdelcontacts , name="otdelcontacts" ),
    path('allresorses/', allresorses , name='allresorses'),
    path('resorsmatch/', resorsmatch , name='resorsmatch'),
    path('rezalt/<int:pk>/', rezalt , name='rezalt'),
    path('companicontacts/<int:pk>/', companicontacts , name='companicontacts'),
    path('allcontactscompani/', allcontactscompani , name='allcontactscompani'),
    path('allcompanis/', allcompanis , name='allcompanis'),
    path('cont/<str:pk>/',mcontactdetail, name='contactsname'),
    path('resorsmatcofall/', resorsmatc_all , name='resorsmatcofall'),
    path('allotd/<str:pk>/',otdelcontacts_all, name='allotd'),
    path('soglos/', soglosovanie_resursu , name = 'soglosov'),
    path('mig/<str:pk>/', makemigratinonresors),
    path('d/', prog ),
]

#

serverrp/serverrp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projects.urls')),
    path('ad/',include('glavarp.urls')),
    path('a/',include('resurses.urls')),
    path('p/',include('post.urls')),
    path('preseil/',include('preseil.urls')),
    path('plan/',include('resorsplaning.urls')),
    path('ut/',include('ushetvremeni.urls')),
    path('b/',include('bazaznaniy.urls')),
    
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

serverrp/resurses/views.py
from .models import Otdel , Zaiyvka , Contacts , Zadatha ,Cotrudniri , PriseofmyWok ,OtchetforMonf ,Compani
from projects.models import Projects , Itap
from preseil.models import PresailProjects
from django.contrib.auth.models import User

from django.contrib.auth.decorators import login_required
from django.conf.global_settings import MEDIA_ROOT
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.core.mail import send_mail , send_mass_mail
from django.db.models import Q
from django.http import FileResponse

from openpyxl import Workbook  , load_workbook
from openpyxl.writer.excel import save_workbook

from datetime import datetime

import os

# Create your views here.
# УДАЛИТЬ _ ПЕРЕДЕЛАТЬ
def main(request):
    pass

# УДАЛИТЬ _ ПЕРЕДЕЛАТЬ
def contacts(request):
    otdel = Otdel.objects.all()
    cont = Contacts.objects.all()
    return render(request, 'resurses/prodject-main.html',{"cont":cont, "otdel":otdel})

# УДАЛИТЬ _ ПЕРЕДЕЛАТЬ
def mycontacts(request, pk):
    #prog = get_object_or_404(Projects, id = pk)
    #otdel = Otdel.objects.filter(projects__title=prog)
    cont = Contacts.objects.all()

    return render(request, 'resurses/prodject-mycontacts.html',{"cont":cont})

#
@login_required(login_url='/lg/')
def mycontactcreate(request, pk):
    prog = get_object_or_404(Projects, id = pk)
    otdel = Otdel.objects.filter(projects__title=prog)
    cont = Contacts.objects.all()

    if request.method == 'POST':
        otdelid = request.POST.getlist('otdelid')
        otdellevel = request.POST.getlist('otdellevel')
        otdeltitle = request.POST.getlist('otdeltitle')
        otdelopisanie = request.POST.getlist('otdelopisanie')
       
        f=0 
        for i in otdelid:
            ot = Otdel.objects.get(id = i)
            ot.title = otdeltitle[f]
            ot.level = otdellevel[f]
            ot.opisanie = otdelopisanie[f]
            ot.save()
            f = f+ 1

        contid = request.POST.getlist('otdelid')
        conttelnomder = request.POST.getlist('conttelnomder')
        conttitle = request.POST.getlist('conttitle')
        contmail = request.POST.getlist('contmail')
        contdoljnost = request.POST.getlist('contdoljnost')
        try:
            g = 0
            for u in contid:
                cont = Contacts.objects.get(id = u)
                cont.telnomder = conttelnomder[g]
                cont.title = conttitle[g]
                cont.mail = contmail[g]
                cont.doljnost = contdoljnost[g]
                cont.save()
                g =g +1 
        except :
            pass
        
        fio = request.POST.getlist('fio')
        telnomnew = request.POST.getlist('telnomnew')
        mailnew = request.POST.getlist('mailnew')
        doljn = request.POST.getlist('doljn')
        iddd = request.POST.getlist('iddd')
        try:
            g = 0
            for inr in iddd:
                cont = Contacts()
                cont.telnomder = telnomnew[g]
                cont.title = fio[g]
                cont.mail = mailnew[g]
                cont.doljnost = doljn[g]
                cont.ondel = Otdel.objects.get(id = inr)
                cont.save()
                g = g+ 1
            
        except:
            pass

        return redirect('projects:views')

    return render(request, 'resurses/prodject-mycontacts-rename.html',{"cont":cont, "otdel":otdel})

# МОИ ЗАДАЧИ 
@login_required(login_url='/lg/')
def myplans(request):
    proj = Projects.objects.filter(rpproecta=request.user.first_name)
    zada = Zadatha.objects.filter(Q(user__first_name=request.user.first_name)|Q(projects__in = proj))
    projd = Projects.objects.all()
    use  = User.objects.all()

    if request.method == 'POST':
        tupe = request.POST.get('tupe')
        if tupe =="new":
            #text = request.POST.get('text')
            le = request.POST.get('projid')
            za = Zadatha()
            za.title = request.POST.get('title')
            za.zada = request.POST.get('text')
            if le == "---":
                pass
            else:
                prod = Projects.objects.get(id=le)
                za.projects = prod
            za.user = request.user
            za.prior = request.POST.get('prior')
            za.srok = request.POST.get('srok')
            za.otvet = request.POST.get('otvet')
            za.save()
        elif tupe == 'old':
            za = Zadatha.objects.get(id = request.POST.get('zadid'))
            za.title = request.POST.get('title')
            za.zada = request.POST.get('text')
            za.prior = request.POST.get('prior')
            za.srok = request.POST.get('srok')
            za.otvet = request.POST.get('otvet')
            za.save()
        elif tupe == 'chec':
            checch = request.POST.getlist('checch')
            for i in checch:
                za = Zadatha.objects.get(id = i)
                za.chec = 'checked'
                za.save()
        elif tupe == 'newtasks':
            prod = Projects.objects.get(id=request.POST.get('projid'))
            #s = request.POST.get('otvet') 
            if  request.POST.get('otvet') == '---':
                us = User.objects.get(first_name=prod.rpproecta)
            else:
                us = User.objects.get(first_name=request.POST.get('otvet'))

            za = Zadatha()
            za.title = request.POST.get('title')
            text = request.POST.get('text')
            za.zada = text
            za.projects = prod
            za.user = us
            za.prior = request.POST.get('prior')
            za.srok = request.POST.get('srok')

            za.otvet = request.POST.get('otvet')
            za.save()
            
            # send_mail(
            #     f'[Системы РМО] Задача по проекту {prod.title}',
            #     f'Новая задача по Проекту:{prod.title}.\r\n  \r\n {text} \r\n  \r\n Системы РМО https://ru01-app38.galaktika.ru/',
            #     'system.pmo@galaktika.ru',
            #     [us.email],
            #     fail_silently=False, 
            #     )
      
        else:
            pass
        return redirect('resurses:myplans')

    return render(request, 'resurses/prodject-myplans.html',{'use':use, 'projd': projd,'proj':proj, 'zada':zada})

# МОЯ КОМАНДА 
@login_required(login_url='/lg/')
def myworkers(request, pk):
    cont = Cotrudniri.objects.filter(projects__id=pk).filter(tip='sotrudnic')
    contac = Cotrudniri.objects.exclude(projects__id=pk).filter(tip='sotrudnic')
    if request.method == 'POST':
        prog = Projects.objects.get(id= pk)
        if request.POST.get('form') == 'del':
            try:
                for u in request.POST.getlist('delete'):
                    cont = Cotrudniri.objects.get(index =u)
                    cont.projects.remove(prog)
                    cont.save()
                
                cont = Cotrudniri.objects.filter(projects__id=pk).filter(tip='sotrudnic')
                contac = Cotrudniri.objects.exclude(projects__id=pk).filter(tip='sotrudnic')
            except:
                pass
        elif request.POST.get('form') == 'searh':
            contac = Cotrudniri.objects.exclude(projects__id=pk).filter(tip='sotrudnic').filter(title__startswith=request.POST.get('s'))
        
        elif request.POST.get('form') == 'add':
            try:
                for u in request.POST.getlist('append'):
                    contac = Cotrudniri.objects.get(index =u)
                    contac.projects.add(prog)
                    contac.save()

                cont = Cotrudniri.objects.filter(projects__id=pk).filter(tip='sotrudnic')
                contac = Cotrudniri.objects.exclude(projects__id=pk).filter(tip='sotrudnic')
            except:
                pass
        else:
            pass
        #return redirect("/a/workers/%s/" % (pk)) 
        return render(request, 'resurses/prodject-myworcers.html',{"cont":cont , 'contac':contac })
    return render(request, 'resurses/prodject-myworcers.html',{"cont":cont , 'contac':contac })

# СОЗДАТЬ СОТРУДНИКА 
@login_required(login_url='/lg/')
def mywokrcrete(request):
    otd = Otdel.objects.all()
    compan = Compani.objects.all()
    if request.method == 'POST':
        cont = Cotrudniri()
        cont.tip = 'sotrudnic'
        cont.title  = request.POST.get('title')
        cont.doljnost = request.POST.get('doljnost')
        cont.mail = request.POST.get('mail')
        cont.ondel = otd.get(id = request.POST.get('otd'))
        cont.telnomder  = request.POST.get('telnomder')
        cont.statusof = request.POST.get('statusof')
        #if request.POST.get('compan') != '':
        #   cont.compan = Compani.objects.get(id =request.POST.get('compan')) 
    
        cont.save()
        return redirect("/a/myworcersall/" ) 
    return render(request, 'resurses/prodject-criate.html',{"otd":otd ,'compan':compan})

# ИЗМЕНИТЬ КОНТАКТ СОТРУДНИК 
@login_required(login_url='/lg/')
def mywokrcrename(request,pk):
    otd = Otdel.objects.all()
    cont = Cotrudniri.objects.get(index = pk)
    compan = Compani.objects.all()
    if request.method == 'POST':
        cont.title  = request.POST.get('title')
        cont.doljnost  = request.POST.get('doljnost')
        cont.mail  = request.POST.get('mail')
        cont.ondel = otd.get(id  = request.POST.get('otd'))
        cont.telnomder  = request.POST.get('telnomder')
        cont.statusof = request.POST.get('statusof')
        if request.POST.get('statusof') == "Уволен":
            cont.datafilds = datetime.now()
        #cont.compan = Compani.objects.get(id =request.POST.get('compan')) 
        cont.save()
        return redirect("/a/myworcersall/" ) 
    return render(request, 'resurses/prodject-criate.html',{"otd":otd ,'con':cont ,'compan':compan})

# ВСЕ КОНТАКТЫ 
@login_required(login_url='/lg/')
def myworcersall(request):
    cont = Cotrudniri.objects.filter(tip='sotrudnic')
    return render(request, 'resurses/prodject-myworcersall.html',{"cont":cont})

serverrp/resurses/templates/resurses/prodject-myworcersall.html
{% extends 'index.html' %}

<!-- титул  -->
{% block page_title %}
<title> Команда проекта </title>
{% endblock %}


{% load static %}
{% load pasport %}
<!-- Стили -->
{% block page_styles %}

<style>

  .containerdert {
  display: block;
  position: relative;
  padding-left: 35px;
  margin-bottom: 12px;
  cursor: pointer;
  font-size: 22px;
  user-select: none;
}

.containerdert input {
  position: absolute;
  opacity: 0;
  cursor: pointer;
  height: 0;
  width: 0;
}

.checkmarkdert {
  position: absolute;
  top: 0;
  left: 0;
  height: 25px;
  width: 25px;
  background-color: #eee;
}

.containerdert:hover input ~ .checkmarkdert {
  background-color: #ccc;
}

.containerdert input:checked ~ .checkmarkdert {
  background-color: #2196F3;
}

.checkmarkdert:after {
  content: "";
  position: absolute;
  display: none;
}

.containerdert input:checked ~ .checkmarkdert:after {
  display: block;
}

.containerdert .checkmarkdert:after {
  left: 9px;
  top: 5px;
  width: 5px;
  height: 10px;
  border: solid white;
  border-width: 0 3px 3px 0;
  -webkit-transform: rotate(45deg);
  -ms-transform: rotate(45deg);
  transform: rotate(45deg);
}
</style>

{% endblock %}

<!-- Слайдер -->
{% block page_slader %}


{% endblock %}

{% block page_contecst %}

<div class="">
  
  <div class="box">
    <div class="box-header with-border">
      <h4 class="box-title"> Сотрудники </h4> 
      <ul class="box-controls pull-right"> 
        <li><a class="box-btn-slide"  href="#"></a></li>	
      </ul>
    </div>
    <div class="box-body">
        <div class="row">
        <div class="col-xl-12 col-12">	
            <div class="table-responsive">
              <table class="table table-hover mb-0">
                <tbody>
                <tr>
                  
                  <th>№</th>
                  <th>ФИО</th>
                  <th>Должность</th>
                  <th>Отдел</th>
                  <th>Почта</th>
                  <th>Телефон</th>
                </tr>
                {% for res in cont %}
                
                <tr>
                  <td> {{ forloop.counter }} </td>
                  <td> <a href="{% url 'resurses:mywokrcrename' pk=res.index %}">{{ res.title }}</a>  </td>
                  <td> {{ res.doljnost }} </td>
                  <td> <a href="{% url 'resurses:myotdel' pk=res.ondel.id %}" >{{ res.ondel.title }}</a> </td> 
                  <td> {{ res.mail }} </td>
                  <td> {{ res.telnomder }} </td>
                </tr>
                
                {% endfor %}
                </tbody>
              </table>
            </div>



        </div>
      </div>
      
    </div>
  </div>
</div>



{% endblock %}

{% block page_staticjsandcss %}



{% endblock %}

serverrp/resurses/templates/resurses/prodject-projects-otdel-all.html
{% extends 'index.html' %}

<!-- титул  -->
{% block page_title %}
<title> Ресурсы </title>
{% endblock %}


{% load static %}
{% load resors %}
<!-- Стили -->
{% block page_styles %}



{% endblock %}

<!-- Слайдер -->
{% block page_slader %}


{% endblock %}

{% block page_contecst %}

<div class="">  
  <div class="box">
    <div class="box-header with-border">
      <h4 class="box-title"></h4> 
      <ul class="box-controls pull-right"> 
        <li><a class="box-btn-slide"  href="#"></a></li>	
      </ul>
    </div>
    <div class="box-body">
        <div class="row">
        <div class="col-xl-12 col-12">	
          <form action="" method="post">
            {% csrf_token %}
          <div class="table-responsive">
            <table class="table table-bordered mb-0">
              <thead>
              <tr>
                <th>№</th>
                <th>ФИО</th>
                <th>Отдел</th>
                <th> Итог </th>
                {% for key in proj %}
                <th>
                  {% if key.rucgrup == "pres" %} 
                    <a href="{% url 'preseil:preselproj' pk=key.id %}">
                      <span class="badge badge-pill badge-info">{{ key.title }}</span>
                    </a>
                  {% else %} 
                  <a href="{% url 'projects:passs' pk=key.id %}">
                    <span class="badge badge-pill badge-warning">{{ key.title }}</span>
                  </a>
                  {% endif %}
                  </th>
                {% endfor %}
              </tr>
            </thead>
            <tbody>
              {% for res in sot %}
              <tr>
                <td> {{ forloop.counter }} </td>
                <td> <a href="{% url 'resurses:mywokrcrename' pk=res.index %}">{{ res.title }}</a>  <!-- <br> {{ res.doljnost }}--> </td>
                <td>  {{ res.ondel.title  }}  </td>
                <td> 
                  {% if res.id|itog:res.index != 100 %}
                  <span class="label label-danger">{{ res.id|itog:res.index  }} </span>
                  {% elif res.id|itog:res.index  == 100 %}
                  <span class="label label-success"> 100 </span>
                  {% endif %}
                </td>
                {% for key in proj%}
                <th  > 
                   {% resors_of_work key.id res.index gor.id  %}
                  
                </th>
                {% endfor %}
              </tr>
              {% endfor %}
            </tbody>
            </table>
          </div>
        </form>
        </div>
      </div>  
    </div>
  </div>

  
</div>

{% endblock %}

{% block page_staticjsandcss %}



{% endblock %}

serverrp/resurses/templates/resurses/prodject-projects-soglos.html
{% extends 'index.html' %}

<!-- титул  -->
{% block page_title %}
<title> Ресурсы </title>
{% endblock %}


{% load static %}
{% load resors %}
<!-- Стили -->
{% block page_styles %}
<style>
  table tbody {
    display: block;
    max-height: 400px;
    overflow-y: scroll;
  }
  
  table thead, table tbody tr {
    display: table;
    width: 100%;
    table-layout: fixed;
  }
  </style>


{% endblock %}

<!-- Слайдер -->
{% block page_slader %}


{% endblock %}

{% block page_contecst %}

<div class="">
  
  <div class="box">
   
    <div class="box-header with-border">
      
      <h4 class="box-title"> Ресурсы</h4> 
      
     
    </div>
    <div class="box-body">
        <div class="row">
        <div class="col-xl-12 col-12">	
          
          <form action="" method="post">
            {% csrf_token %}
            <div class="table-responsive">
              <table class="table table-hover mb-0">
                <thead>
                <tr>
                  <th width='10px'>№</th>
                  <th width='150px'> ФИО </th>
                  {% for i in prog %}
                  <th width='130px'>
                  {% if i.rucgrup == "pres" %} 
                  <a href="{% url 'preseil:preselproj' pk=i.id %}">
                    <span class="badge badge-pill badge-info">{{ i.title }}</span>
                  </a>
                  {% else %} 
                  <a href="{% url 'projects:passs' pk=i.id %}">
                    <span class="badge badge-pill badge-warning">{{ i.title }}</span>
                  </a>
                  {% endif %}
                  </th>
                  {% endfor %}
                </tr>
              </thead>
              <tbody>
                {% for h in cont %}
                <tr>
                <th width='10px'>{{ forloop.counter }}</th>
                <th width='150px'>{{ h.title }} </th>  
                {% for i in prog %}
                  <th width='130px'> 
                    {% checmyresors i.id h.index  as prod %}
                    {% if prod != 'non' %}
                    <input type="hidden" name="checid" value="{{ i.id }}?{{ h.index }}"  >
                    <select class="form-control select2"  name="proz"  title=" {{ i.title }} | {{ h.title }}"> 
                      <option value="{{ prod }}">{{  prod }}%</option>
                      <option value="0">0%</option>
                      <option value="10">10%</option>
                      <option value="20">20%</option>
                      <option value="30">30%</option>
                      <option value="40">40%</option>
                      <option value="50">50%</option>
                      <option value="60">60%</option>
                      <option value="70">70%</option>
                      <option value="80">80%</option>
                      <option value="90">90%</option>
                      <option value="100">100%</option>
                    </select>   
                    {% endif %}
                  </th>
                {% endfor %}
                </tr>
                {% endfor %}
              </tbody>
                
              </table>
            </div>

            <div class="">
              
              <input type="submit" value="Утвердить расход ресурсов" class="btn btn-group-lg btn-block btn-success" > 
             
            </div>
            
          </form>

        </div>
      </div>
      
    </div>
  
  </div>
 

</div>



{% endblock %}

{% block page_staticjsandcss %}



{% endblock %}

serverrp/resurses/templates/resurses/projects-compani-contacts-all.html
{% extends 'index.html' %}

<!-- титул  -->
{% block page_title %}
<title> Контакты </title>
{% endblock %}


{% load static %}
{% load resors %}
<!-- Стили -->
{% block page_styles %}


{% endblock %}

<!-- Слайдер -->
{% block page_slader %}


{% endblock %}

{% block page_contecst %}
<div class="">
  <div class="box">
    <div class="box-body ">
<div class="flexbox align-items-center p-15">
<div class="flexbox align-items-center">
  <div class="custom-control custom-checkbox pl-0">
  <button type="button" class="btn btn-default btn-sm checkbox-toggle"><i class="ion ion-android-checkbox-outline-blank"></i></button>
  </div>

  <span class="divider-line mx-1"></span>

 
  <div class="dropdown d-none d-lg-block">
  <button class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" aria-expanded="false">Компании</button>
  <div class="dropdown-menu">
    {% for i in comp %}
    <a class="dropdown-item" href="{% url 'resurses:companicontacts' pk=i.id %} ">{{ i.title}}</a> 
   
    {% endfor %}
  </div>
  </div>
</div>

<div>
  <div class="lookup lookup-circle lookup-right">
  <input type="text" data-provide="media-search">
  </div>
</div>
</div>

<div class="media-list media-list-divided media-list-hover">
{% for res in cont %}
<div class="media align-items-center">
  <div class="custom-control custom-checkbox">
  <input type="checkbox" class="custom-control-input">
  </div>

  

  

  <img class="avatar" src="{% static "projects/images/avatar/1.jpg" %}" alt="...">

  <div class="media-body text-truncate">
    <h6><a href="{% url 'resurses:contactsname' pk=res.index  %}" >  {{ res.title }} </a> </h6>
    <span> {{ res.doljnost }}  </span> <br>
    <small>
    <span>{{ res.mail }} </span>
    <span class="divider-dash">{{ res.telnomder }}</span>
    </small>
  </div>
  </a>
  
  <ul class="list-inline">
  <li><a class="hover-secondary" href="{% url 'resurses:companicontacts' pk=res.compan.id %}"><i class="fa fa-industry"></i>  {{ res.compan.title }}</a></li>
  
  </ul>
  
  <div class="dropdown">
  <a class="text-lighter" href="#" data-toggle="dropdown"><i class="ti-more-alt rotate-90"></i></a>
  <div class="dropdown-menu dropdown-menu-right">
    <a class="dropdown-item" href="{% url 'resurses:companicontacts' pk=res.compan.id %}"><i class="fa fa-fw fa-industry"></i> Компания</a>
    <a class="dropdown-item" href="#"><i class="fa fa-fw fa-commenting"></i> Message</a>
    <a class="dropdown-item" href="#"><i class="fa fa-fw fa-envelope"></i> Email</a>
    
  </div>
  </div>
</div>
{% endfor %}

</div>
    </div>
    <!-- /.box-body -->
  </div>
  <!-- /. box -->
</div>




{% endblock %}

{% block page_staticjsandcss %}



{% endblock %}