serverrp/post/urls.py
from django.urls import path , include
from post.views import post_page ,post_page_generate , post_page_name , post_dowlend


app_name='post'

urlpatterns = [
    path('', post_page, name='postpage'), 
    path('<str:pk>/', post_page_generate, name='postpagegenerate'), 
    path('name/<str:pk>/', post_page_name, name='postname'), 
    path('file/<str:pk>/', post_dowlend, name='pismofile'), 
]

serverrp/projects/urls.py
from django.urls import path , include
from projects.views import(
    projects_views , projects_detail, otchet , logout_view, logins , projects_detail_st_low , list_otch ,dashboard_allprod,
    projects_views_all, dashbotrd_pass, dashboard_pasport , dashboard_myprod ,dashboard_operplan ,
    pmo_main_page ,pmo_post_page,  deshbord_prodj,  pasport_red,
    check , dashbord_pocaz , otchet_new , del_sotr_from
)

app_name='projects'

urlpatterns = [
    path('', projects_views, name='views'), # все проекты / Мои проекты (отчеты)
    path('<int:pk>/',projects_detail,name='detail'), # отче проекта
    path('otch/',otchet,name='otch'),#  отчет для М
    path('otch2/',otchet_new,name='otchetnew'),#  отчет для М 2
    path('logout/',logout_view ,name='logout'),# Выйти
    path('lg/', logins ,name='ligin'),# Войти 
    path('st/<int:pk>/', projects_detail_st_low,name='detail_st'),# Отчет проекта- Степанова
    path('ch/', check , name='chrck'),# Проверка обновления Обновить код 
    path('pmomaim/',pmo_main_page, name="pmo"),# PMO
    path('pmopost/',pmo_post_page, name="pmopost"),#  РМО paccылка
    path('allprod/' ,dashboard_allprod , name="allprod"),# Все проекты (Пас)
    path('myprod/' ,dashboard_myprod , name="myprod"),# Мои проекты (Пас)
    path('proect/<int:pk>/' ,dashboard_pasport , name="passs"),# Паспорт проекта 
    path('operplam/<int:pk>/',dashboard_operplan, name="operplan"),# Обновить говно полное  
    path('dashboard/' , deshbord_prodj , name="dashbord"),# Доработаь 
    path('ot/', list_otch ,name='list'),# Общий отчет с возможностью менять (Перписать)
    path('all/', projects_views_all , name='all'),#Все проекты  (отчеты)
    path('otshetpass/',dashbotrd_pass, name='dashpass' ), # Отчет таблица общий без сылок 
    path('pasportre/<int:pk>/',pasport_red, name="pasportre"), # редактировать информацию по проекту 

    path('del/<int:pk>/<str:cot>/', del_sotr_from , name='del_sort_form'  ), # Удалить сотрудкника 

    path('pok/<int:pk>/',dashbord_pocaz, name="pok"),# удалить нахер 
    #path('test/', projects_views2 , name='views2'),# ТеСТ
    #path('creat/',crete_prodjects, name='create'),# удалить нахер 
    #path('proect/', projects_moiproecs, name='moipr'),# Удалить не актуально
    #path('mig/', from_exel_to_sql),#удалить нахер 
    #path('pasport/<int:pk>/',dashbord_pocaz, name="pasport"),# удалить нахер 
    #path('pasport/ch/<int:pk>', pr_pasport_red, name="pasportred"),#удалить нахер 
    #path('zadatha/',zadatha, name = "zadatha" ),#удалить нахер 
    #path('zadath/<int:pk>' , zadaniadetail , name="zadditail"),#удалить нахер 
    #path('zadathamoi/',zadathamoi, name = "zadathamoi"),#удалить нахер 
    #path('zadathvse/<int:pk>' ,zadathavse , name="zadathavse"),#удалить нахер 
    #path('create/',   dashboard_create, name='creates') # Надо доделать, а лучше перенести в другой модуль 
]

serverrp/serverrp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projects.urls')),
    path('ad/',include('glavarp.urls')),
    path('a/',include('resurses.urls')),
    path('p/',include('post.urls')),
    path('preseil/',include('preseil.urls')),
    path('plan/',include('resorsplaning.urls')),
    path('ut/',include('ushetvremeni.urls')),
    path('b/',include('bazaznaniy.urls')),
    
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

serverrp/projects/forms.py
from django import forms
from django.forms.formsets import formset_factory
from django.forms import ModelForm

from .models import Projects ,Itap


class ItapApdete(forms.Form):
    
    komentrp = forms.CharField(widget=forms.Textarea, required=False)

    act = forms.CharField(widget=forms.Textarea, required=False)

    oplata = forms.CharField(widget=forms.Textarea, required=False)

    
class ItapAP(ModelForm):
    class Meta:
        model = Itap
        fields = ['komentrp']    

    
class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()
    

serverrp/projects/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from .models import Projects , Itap , Komanda , Zadania , Dopsog , Zadachirp , Risk , Problems , Mani , Documents , Cost , ProductProd , HistoriOfTheOtchet
from .forms import ItapApdete , ItapAP, UploadFileForm
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login ,logout
from django.contrib.auth.models import User
from django.core.mail import send_mail , send_mass_mail
from resurses.models import Otdel ,Zadatha , Contacts ,Cotrudniri , Compani , PriseofmyWok ,OtchetforMonf 
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render
from datetime import datetime , timedelta 
import openpyxl
import pytz
import calendar

from django.contrib.auth.decorators import login_required

# Create your views here.

def otchet_new(request):
    itap = Itap.objects.all()
    proj = Projects.objects.filter(otchtetm='Д').exclude(activedog = "Завершен").exclude(activedog = "Системный")
    return render(request, 'projects/otchet-new.html',{'projects':proj,'itap':itap})

# Все проекты отчет общий (без редактироания)
def dashbotrd_pass(request):
    itap = Itap.objects.all()
    proj = Projects.objects.exclude(activedog = "Завершен").exclude(activedog = "Системный")
    return render(request, 'projects/prodject-dashbord-pass.html',{'projects':proj,'itap':itap})
# Редактироание Паспартов
def pasport_red(request,pk):
    projects = get_object_or_404(Projects, id=pk)
    comp = Compani.objects.all()
    try:
        compannn = Compani.objects.get(id=projects.compani)
    except:
        compannn = {"title":"-"}
    #otdel = Otdel.objects.filter(projects__title=projects).first()
    users = User.objects.all()
    itap= Itap.objects.filter(projects__title=projects)
    if request.method == 'POST':
        dd = request.POST.get('form')
        if dd == "newcompani":
            c = Compani()
            c.title = request.POST.get('title')
            c.opisanie = request.POST.get('otvet')
            c.save()
            c = Compani.objects.get(title=request.POST.get('title'))
            pr = Projects.objects.get(id= pk)
            pr.compani = c.id
            pr.save()

        else:
            itid = request.POST.getlist('itid')
            datastart = request.POST.getlist('datastart')
            datastop = request.POST.getlist('datastop')
            itapnaim = request.POST.getlist('itapnaim')
            itaptitle =  request.POST.getlist('itaptitle')
            g = 0
            for i in itid:
                try:
                    it = Itap.objects.get(id= i)
                
                    it.datastart =  datastart[g]
                    it.datastop =  datastop[g]
                    it.itapnaim = itapnaim[g]
                    it.title = itaptitle[g]
                    it.save()
                    try:
                        mo = Mani.objects.get(itap= it )
                    except:
                        mo = Mani()
                        mo.title = it.title
                        mo.itap = it
                        mo.save()
                    g= g+1
                except:
                    g= g+1

            titlenew = request.POST.get('titlenew')
            itapnaimnew = request.POST.get('itapnaimnew')
            datastartnew = request.POST.get('datastartnew')
            datastopnew = request.POST.get('datastopnew')
            pr = Projects.objects.get(id= pk)

            if titlenew != ' ':
                try:
                    #str(str(int(a[2]))+'-'+a[1]+'-'+a[0])
                    #str(str(int(b[2]))+'-'+b[1]+'-'+b[0])
                    #a = datastartnew.split('.')
                    #b = datastopnew.split('.')
                    it = Itap()
                    it.title = titlenew
                    it.itapnaim = itapnaimnew
                    it.datastart = datastartnew
                    it.datastop = datastopnew
                    it.komentrp =  ''
                    it.komentstep = '' 
                    it.projects = pr
                    it.save()

                except:
                    pass
            else:
                pass

            pr.nomerdogovora = request.POST.get('nomerdogovora') 
            pr.rpproecta = request.POST.get('rpproecta')
            pr.sistema = request.POST.get('sistema')
            pr.prisezatrat = request.POST.get('prisezatrat')
            pr.prisepr = request.POST.get('prisepr')
            pr.tipdogovora = request.POST.get('tipdogovora')
            

            zakazchic = request.POST.get('zakazchic')
            if zakazchic == "None" or zakazchic == "-":
                pass
            else:
                pr.compani = zakazchic
            pr.save()

        return redirect('projects:myprod') 

    return render(request, 'projects/prodject-dashbord-pasport-rename.html',{ "users":users, "projects":projects,'itap':itap ,'comp':comp ,'compannn':compannn})
# ПМО главная 
def pmo_main_page(request):
    use = User.objects.all()
    return render(request, 'projects/prodject-pmo.html',{'use':use})
# ПМО рассылка 
def pmo_post_page(request):
    use = User.objects.all()
    mails = []
    for e in use:
        if e.email == '':
            pass
        else:
            mails.append(e.email)
    try:
        mails.append('makeev.m@galaktika.ru')
        send_mail(
                '[Системы РМО] Отчет по проектам',
                'Добрый день, коллеги.\r\n  \r\n Прошу обновить статус отчет по Вашим проектам на портале: https://ru01-app38.galaktika.ru/',
                'system.pmo@galaktika.ru',
                mails,
                fail_silently=False,
                
                )
        post = "Сообщения отправлены"
    except:
        post = "Сообщения HE отправлены "
        
    return render(request, 'projects/prodject-pmo.html', {'post':post,'use':use})
# выйти
def logout_view(request):
    success_url = reverse_lazy('projects:ligin')
    logout(request)
    return redirect(success_url)
# Войти 
def logins(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        try:
            if user is not None:
                login(request, user)
                return redirect('projects:myprod')
            else: 
                return redirect('projects:ligin')
        except:
            return redirect('projects:ligin') 
    return render(request, 'projects/prodject-login.html' )
# Все проекты (Отчеты)

@login_required(login_url='/lg/')
def projects_views_all(request):
    itap = Itap.objects.all()
    proj = Projects.objects.exclude(activedog__in = ["Завершен", "Системный"])
    if request.method == 'POST':
        proj = proj.filter(title__startswith=request.POST.get('s'))
        return render(request, 'projects/prodject-dashbord.html',{'projects':proj,'itap':itap })
    return render(request, 'projects/prodject-dashbord.html',{'projects':proj,'itap':itap})
#  Все проекты / Мои проекты (отчеты)
@login_required(login_url='/lg/')
def projects_views(request):
    try:
        if request.user.username == 'stepanova' or request.user.username == 'boss' or request.user.username == 'malkov' :
            itap = Itap.objects.all()
            proj = Projects.objects.filter(Q(activedog ="В работе") | Q(activedog ="Приостановлен"))
            if request.method == 'POST':
                proj = proj.filter(title__startswith=request.POST.get('s'))
                return render(request, 'projects/prodject-dashbord.html',{'projects':proj,'itap':itap })
            return render(request, 'projects/prodject-dashbord.html',{'projects':proj,'itap':itap })
        else:
            proj = Projects.objects.filter(rpproecta=request.user.first_name).filter(Q(activedog ="В работе") | Q(activedog ="Приостановлен"))
            itap = Itap.objects.all()
            if request.method == 'POST':
                proj = proj.filter(title__startswith=request.POST.get('s'))
                return render(request, 'projects/prodject-dashbord.html',{'projects':proj,'itap':itap })
            return render(request, 'projects/prodject-dashbord.html',{'projects':proj,'itap':itap })    
    except:
        return redirect('projects:ligin')
#   Отчет М    
def otchet(request): 
    itap = Itap.objects.all()
    proj = Projects.objects.exclude(activedog = "Системный")
    otch = 'Д'
    
    return render(request, 'projects/otchet.html',{'projects':proj,'itap':itap,'otch':otch })
# Возможность редактироать все проекты (Доработаь ) _______ПЕРЕПИСАТЬ 
@login_required(login_url='/lg/')
def list_otch(request):
    itap = Itap.objects.all()
    proj = Projects.objects.exclude(activedog = "Системный")
    
    if request.method == 'POST':
        form =ItapAP(request.POST)
        otchm = request.POST.getlist('otchm')
        step = request.POST.getlist('komentstep')
        rpot = request.POST.getlist('komentrp')
        zad = request.POST.getlist('zadolkjnost')
        itapid = request.POST.getlist('iditap')

        if form.is_valid():
            vin = 0
            for k in proj:
                pro = Projects.objects.get(id=k)
                pro.otchtetm = otchm[vin]
                pro.save()
                vin=vin+1

            vid = 0
            for ot in itapid:
                try:
                    ots = Itap.objects.get(id=ot)
                    ots.komentstep =step[vid]
                    ots.komentrp = rpot[vid]
                    ots.zadolkjnost = zad[vid]
                    ots.save()
                    vid=vid+1
                except:
                    vid=vid+1
                    print(ot)

        return redirect('projects:views')
    return render(request, 'projects/prodject-pmo-vseproecty.html',{'projects':proj,'itap':itap})
# Проверка обновления _______ПЕРЕПИСАТЬ
@login_required(login_url='/lg/')

serverrp/projects/templates/projects/otchet.html
<!DOCTYPE html>
{% load static %}
{% load pasport %}
<html>
<head>
    <meta charset="utf-8" />
    <title>
    Отчет по проектам.
    </title>
    <style type="text/css">
        A:link {text-decoration: none; color: #FFFF00; /* Убирает подчеркивание для ссылок */} 
        A:visited { text-decoration: none; color: #FFFF00; /* Цвет ссылки */} 
        A:active { text-decoration: none; color: #FFFF00; }
        A:hover { text-decoration: underline; /* Делает ссылку подчеркнутой при наведении на нее курсора */  color: #FFFF00; /* Цвет ссылки */} 
        table.fed { 
            border-collapse: collapse;
            border-radius:15px;
            box-shadow: 0 0 0 3px #FFFFFF;
            }/* cellspacing="0" cellpadding="4" border="1" */
        td.dom {
            border-collapse: collapse;
            border-radius: 12px;
            box-shadow: 0 0 0 5px #FF00FF;
        }
    
    </style>
</head>
<body bgcolor="#166858" style="color:#FFFFFF; font-family: 'Times New Roman', Times, serif" >
 
    
       

        <a href="{% url 'projects:views' %}"> Все проекты </a>
        <a href="{% url 'projects:ligin' %}"> Войти </a>
        
        <h1 align="center"> ОТЧЕТ ПРОЕКТНОГО ОФИСА  </h1>
        
        <h2 align="center"> {% now "j.m.o" %} г. </h1>
        
        {% for itm in projects %}
        {% if itm.activedog != "Завершен" %}
            {% if itm.otchtetm == 'Д' %}    

        <img src="{% static "projects/lin.png" %}" width="100%" height="25">   
           
        <table width="100%"> 
            <tr>
                <td width="50" align="right"> <img src="{% static "projects/zavod.png" %}" width="80" height="80" ></td>
                <td width="100"> <h1><a href=
                {% if user.username == "stepanova" %}
                    "{% url 'projects:detail_st' pk=itm.id %}" 
                {% else %}
                    "{% url 'projects:detail' pk=itm.id %}" 
                {% endif %}    
                    >{{ itm.title|upper  }}</a> </h1></td>
                <td width="50" align="right" > <img src="{% static "projects/rp.png" %}" width="50" height="50" ></td>
                <td width="100"><h2>{{ itm.rpproecta|upper  }}</h2> </td>
            </tr>
        </table>
                    
                {% for itms in itap|it:itm.id %}
                    {% if itms.projects.title == itm.title %}

                        {% if itms.komentrp %}  
                    <table width="100%" >
                        <tr>
                            <td align="right" width="45%" ><img src="{% static "projects/itap.png" %}" width="40" height="40"> </td><td  align="left"><h1 > {{ itms.title|upper  }} </h1> </td> <td width="10%"> </td>
                        </tr>
                    </table>

                    <table width="100%" >
                        <tr>
                            <td width="16%" align="right" ><img src="{% static "projects/data.png" %}" width="45" height="40"></td>
                            <td width="16%"  > <h1>{{ itms.datastop|date:"d.m.Y" }}</h1></td>
                            <td width="16%" align="right" ><img src="{% static "projects/datar.png" %}" width="50" height="50"></td>
                            <td width="16%"> <h2>{{ itms.oplata|upper }}</h2></td>
                            <td width="16%" align="right" ><img src="{% static "projects/mone.png" %}" width="45" height="45"></td>                     
                            <td width="16%"><h2>{{ itms.act|upper }}</h2> </td>
                        </tr>
                    </table>

                    <table width="100%" >
                        <tr>
                            <td width="10%" valign="top" align="right">
                                <img src="{% static "projects/kom.png" %}" width="70" height="70">
                            </td>
                            <td>
                                {% if itms.act in "Подписан" and  itms.oplata in "Оплачен" %}
                                <p>Завершен и оплачен</p> 
                                {% endif %}
                               {{ itms.komentrp }}
                            </td>
                        </tr>
                        {% if itms.komentstep %}  
                        <tr>
                            <td width="10%" valign="top"  align="right"> 
                                <img src="{% static "projects/kom.png" %}" width="70" height="70">
                            </td>
                            <td class="dom">
                                 <p>Комментарий Ирины Степановой: <br>
                                    <b> {{ itms.komentstep }}</p>        
                            </td>
                        </tr>
                        {% endif %}
                    </table>
                    <br>
                        {% endif %}                     
                    {% endif %}
                 {% endfor %}
            {% endif %}
            {% endif %}
        {% endfor %}

                    <img src="{% static "projects/lin.png" %}" width="100%" height="25">  
                    <h1 align="center" style="color:#FFFF00"> ПРОСРОЧЕННАЯ ДЕБИТОРСКАЯ ЗАДОЛЖЕННОСТЬ </h1>
    {% for itm in projects %}
    {% for itms in itap|itapzadolg:itm.id %}
    
            
                <table width="100%" class="fed" >
                <tr >
                    <td width="10%" align="right" ><img src="{% static "projects/zavod.png" %}" width="30" height="30"></td>
                    <td width="15%" align="left"> <h1>{{ itm.title }}</h1></td>
                    <td width="10%" align="right" ><img src="{% static "projects/itap.png" %}" width="30" height="30"></td>
                    <td width="20%" align="left"> <h1>{{ itms.title }}</h1> </td>
                    <td width="10%" align="right" ><img src="{% static "projects/mone.png" %}" width="30" height="30"></td>
                    <td width="20%" align="left"> <h1>{{ itms.zadolkjnost }} Р.</h1> </td>
                </tr>
                <tr >
                        <td> </td>
                        <td align="right" ><img src="{% static "projects/data.png" %}" width="30" height="30"></td>
                        <td width="70%" align="left" colspan="5">     
                                <h1>ОЖИДАЕМЫЙ СРОК ОПЛАТЫ -</h1> 
                        </td>
                        
                        
                </tr>
            </table> <br>
                
                
    {% endfor %}  
    {% endfor %}              


</body>
</html>

serverrp/projects/templates/projects/prodject-dashbord.html
{% extends 'index.html' %}

<!-- титул  -->
{% block page_title %}
<title> Отчет по Проекту </title>
{% endblock %}

{% load static %}
{% load pasport %}
<!-- Стили -->
{% block page_styles %}


{% endblock %}

<!-- Слайдер -->
{% block page_slader %}

<li class="header">Проекты</li>  
		  
        <li class="treeview">
          <a href="#">
            <i class="ti-palette"></i>
            <span>Проекты </span>
            <span class="pull-right-container">
              <i class="fa fa-caret-down pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">

			
			{% for itm in projects %}

            <li><a href="#{{ itm.id }}"><i class="fa fa-circle-thin"></i>{{ itm.title }}</a></li>
            
			
			{% endfor %}
          </ul>
</li>

{% endblock %}

<!-- Основной контент -->
{% block page_contecst %}



        <div class="">
                <div class="box">
                    <form  method="post">
                      <div class="box-header">
                          <h4 class="box-title"> Отчеты </h4>
                            {% csrf_token %}
                          <div class="box-controls pull-right">
                            
                            <div class="lookup lookup-circle lookup-right">
                              <input type="text" name="s"><input type="submit" hidden> 
                            </div>
                          </div>
                        
                    </div>
                    </form>
                    <!-- /.box-header -->
                    <div class="box-body no-padding">
                        <div class="table-responsive">
                          <table class="table table-hover">
                            <tr>
                                <th scope="col">Проект</th>
                                <th scope="col">Этап</th>
                                <th scope="col">Дата завершения</th>
                                <th scope="col">План </th>
                                <th scope="col">Факт </th>
                                <th scope="col">Акт </th>
                                <th scope="col">Оплата </th>
                                <th scope="col">Комментарий</th>
                            </tr>
                            
                            {% for itm in projects %}
                            
                            
                            <tr bgcolor="{% cycle '#E6E6E6' '#FFFFFF' as tablecolor %}" class="tab"> 
                                    
                                <td  rowspan="{{itm.id|itcount}}">
                                <a class ="Fig" href=
                                {% if user.username == "stepanova" %}
                                    "{% url 'projects:detail_st' pk=itm.id %}" 
                                {% else %}
                                    "{% url 'projects:detail' pk=itm.id %}" 
                                {% endif %}    
                                name="{{ itm.id }}">
                                {{ itm.title }} <br> РП: {{ itm.rpproecta }} <br> {{ itm.nomerdogovora }} <br> {{ itm.tipdogovora }}</td> 
                                </a> 
                            
                            
                                {% for itms in itap|itapfiltersfor:itm.id %}
                                    
                                    <td bgcolor="{{ tablecolor }}" class="col-xs-2"> {{ itms.title }} {{ itms.itapnaim|truncatechars:50 }}</td> 
                                    
                                    <td bgcolor="{{ tablecolor }}"> {{ itms.datastop|date:"d.m.Y"  }}</td> 
                                    <td bgcolor="{{ tablecolor }}"> {{ itms.id|hi  }}</td> 
                                    <td bgcolor="{{ tablecolor }}"> {{ itms.id|prozent }} %</td> 
                                    <td bgcolor="{{ tablecolor }}">   
                                    {% if itms.act == "Подписан" %}
                                      <img src="{% static "projects/icon1.png" %}" width="25" height="25" title="{{ itms.act }}">
                                    {% elif itms.act == "Не начат" or itms.act == "В работе" %}
                                      <img src="{% static "projects/icon2.png" %}" width="25" height="25" title="{{ itms.act }}">
                                    {% elif itms.act == "Сформирован" %}
                                      <img src="{% static "projects/icon5.1.jpeg" %}" width="25" height="25" title="{{ itms.act }}">
                                    {% elif itms.act == "На подписании" %}
                                      <img src="{% static "projects/sig.png" %}" width="25" height="25" title="{{ itms.act }}">
                                   
                                    {% else %}
                                      <!-- {{ itms.act }}-->
                                    {% endif %}
                                    </td>
                                    <td bgcolor="{{ tablecolor }}"> 
                                    {% if itms.oplata == "Оплачен" %}
                                        <img src="{% static "projects/icon4.png" %}" width="25" height="25" title="{{ itms.oplata }}">
                                    {% elif itms.oplata == "Задолженность" %}
                                        <img src="{% static "projects/icon3.png" %}" width="25" height="25" title="{{ itms.oplata }}">
                                    {% elif itms.oplata == "Ожидаем" %}
                                        <img src="{% static "projects/time.png" %}" width="25" height="25" title="{{ itms.oplata }}">
                                    {% elif itms.oplata == "Не начат" or itms.oplata == "В работе" %}
                                        <img src="{% static "projects/icon2.png" %}" width="25" height="25" title="{{ itms.oplata }}">
                                    {% else %}
                                       <!--  {{ itms.oplata }}-->
                                    {% endif %} 
                                    </td>
                                    <td bgcolor="{{ tablecolor }}" > 
                                        {% if itms.act in "Подписан" and  itms.oplata in "Оплачен" %}
                                                <p style="color: #006400">Завершен/Оплачен</p> 
                                        {% elif itms.act in "Подписан" and  itms.oplata in "Ожидаем" %}
                                                <p style="color: #006400"> Акт подписан/ <span style="color: #ff0a0a">Ожидает оплаты.</span> </p> 
                                        {% endif %}
                                        
                                        {{ itms.komentrp }}
                                        {% if itms.komentstep %}
                                            <br><br><strong> Комментарий Ирины Степановой: </strong>
                                                <br> {{ itms.komentstep }} 
                                        {% endif %}
                                    </td>
                                    </tr> 
                                    
                                {% endfor %}  
                                
                              
                        {% endfor %} 


                          </table>
                        </div>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
      

{% endblock %}

serverrp/projects/templates/projects/prodject-pmo.html
{% extends 'index.html' %}

<!-- титул  -->
{% block page_title %}
<title> ПМО</title>
{% endblock %}

{% load static %}
{% load pasport %}
<!-- Стили -->
{% block page_styles %}

{% endblock %}

<!-- Слайдер -->
{% block page_slader %}


<li>
    <a href="{% url 'projects:pmopost' %}" hidden>
      <i class="ti-email"></i>
<span>Разослать письма <br> {{ post }}</span>
    </a>
  </li>	
<li>
    <a href="{% url 'projects:list' %}">
      <i class="ti-calendar"></i>
<span>Все проекты</span>
    </a>
  </li>		  
<li>
    <a href="{% url 'projects:chrck' %}">
      <i class="ti-pencil-alt"></i>
<span>Проверка обновления</span>
    </a>
</li>


{% endblock %}

<!-- Основной контент -->
{% block page_contecst %}


<div class="table-responsive">
    <!-- Projects table -->
    <table  class="table align-items-center table-flush" >
      <thead class="thead-light">
        <tr>
          <th scope="col" >Login </th>
          <th scope="col" >Имя пользователя</th>
          <th scope="col">Последнее логирование</th>
          <th scope="col">Email</th>
        </tr>
      </thead>
      <tbody >
      {% for int in use %}
          <tr bgcolor="{% cycle '#DCDCDC' '#FFFFFF' as tablecolor %}">
              <td> {{ int.username }}</td> <td> {{ int.first_name }} </td> <td> {{ int.last_login }}</td> <td> {{ int.email }}</td> 
          </tr>
      {% endfor %}
        
      </tbody>
    </table>
  </div>

{% endblock %}