serverrp/post/urls.py
from django.urls import path , include
from post.views import post_page ,post_page_generate , post_page_name , post_dowlend


app_name='post'

urlpatterns = [
    path('', post_page, name='postpage'), 
    path('<str:pk>/', post_page_generate, name='postpagegenerate'), 
    path('name/<str:pk>/', post_page_name, name='postname'), 
    path('file/<str:pk>/', post_dowlend, name='pismofile'), 
]

serverrp/preseil/urls.py
from django.urls import path , include
from preseil.views import (
    preseilmain , preseilmainall , preseilmainmy ,preseilnew ,presailotchet
)
app_name='preseil'

urlpatterns = [
    path('<int:pk>/', preseilmain, name='preselproj'), 
    path('', preseilmainmy, name='presailall'), 
    path('all/', preseilmainall, name='presail'), 
    path('new/', preseilnew, name='presailnew'), 
    path('otch/', presailotchet, name='presailotchet'), 
]

serverrp/serverrp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projects.urls')),
    path('ad/',include('glavarp.urls')),
    path('a/',include('resurses.urls')),
    path('p/',include('post.urls')),
    path('preseil/',include('preseil.urls')),
    path('plan/',include('resorsplaning.urls')),
    path('ut/',include('ushetvremeni.urls')),
    path('b/',include('bazaznaniy.urls')),
    
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

serverrp/preseil/views.py
from django.shortcuts import render , redirect
from django.contrib.auth.decorators import login_required
from preseil.models import PresailProjects, StadiiProdaj ,KomentForPresail ,  ProductOf  , PresProjNew
from django.contrib.auth.models import User
from resurses.models import Compani , Cotrudniri , PriseofmyWok , OtchetforMonf
from projects.models import ProductProd
# Create your views here.

@login_required(login_url='/lg/')
def preseilmainall(request):
    press = PresProjNew.objects.exclude(status='Отказ').exclude(status='Завершен')
    use = User.objects.all()
    prod = ProductProd.objects.all() 
    if request.method == 'POST':
        rp = request.POST.get('rp')
        products = request.POST.get('product')
        polzvt = request.POST.get('polzvt') 
        status = request.POST.get('status')
        #sum1 = request.POST.get('sum1')
        #sum2 = request.POST.get('sum2')
        #kanal = request.POST.get('kanal') 
        if polzvt !='-' and status != '-' and rp != '-' and products != '-':
            press = PresProjNew.objects.filter(rpproecta=rp).filter(status=status).filter(polzvt=polzvt).filter(products=products)

        elif polzvt =='-' and status == '-' and rp == '-' and products != '-':
            press = PresProjNew.objects.filter(products=products)
        elif polzvt =='-' and status == '-' and rp != '-' and products == '-':
            press = PresProjNew.objects.filter(rpproecta=rp)
        elif polzvt =='-' and status != '-' and rp == '-' and products == '-':
            press = PresProjNew.objects.filter(status=status)
        elif polzvt !='-' and status == '-' and rp == '-' and products == '-':
            press = PresProjNew.objects.filter(polzvt=polzvt)

        elif polzvt =='-' and status != '-' and rp != '-' and products != '-':
            press = PresProjNew.objects.filter(rpproecta=rp).filter(status=status).filter(products=products)
        elif polzvt !='-' and status == '-' and rp != '-' and products != '-':
            press = PresProjNew.objects.filter(rpproecta=rp).filter(polzvt=polzvt).filter(products=products)
        elif polzvt !='-' and status != '-' and rp == '-' and products != '-':
            press = PresProjNew.objects.filter(status=status).filter(polzvt=polzvt).filter(products=products)
        elif polzvt !='-' and status != '-' and rp != '-' and products == '-':
            press = PresProjNew.objects.filter(rpproecta=rp).filter(status=status).filter(polzvt=polzvt)

        elif polzvt =='-' and status == '-' and rp != '-' and products != '-':
            press = PresProjNew.objects.filter(rpproecta=rp).filter(products=products)
        elif polzvt !='-' and status == '-' and rp == '-' and products != '-':
            press = PresProjNew.objects.filter(polzvt=polzvt).filter(products=products)
        elif polzvt !='-' and status != '-' and rp == '-' and products == '-':
            press = PresProjNew.objects.filter(status=status).filter(polzvt=polzvt)
        elif polzvt =='-' and status != '-' and rp != '-' and products == '-':
            press = PresProjNew.objects.filter(rpproecta=rp).filter(status=status)

        elif polzvt =='-' and status != '-' and rp == '-' and products != '-':
            press = PresProjNew.objects.filter(status=status).filter(products=products)
        elif polzvt !='-' and status == '-' and rp != '-' and products == '-':
            press = PresProjNew.objects.filter(rpproecta=rp).filter(polzvt=polzvt)
        elif polzvt =='-' and status != '-' and rp == '-' and products != '-':
            press = PresProjNew.objects.filter(status=status).filter(products=products)
        elif polzvt !='-' and status != '-' and rp == '-' and products == '-':
            press = PresProjNew.objects.filter(status=status).filter(polzvt=polzvt)


        else:
            press = PresProjNew.objects.all()


        #press = PresProjNew.objects.filter(rpproecta=rp).filter(status=status)
        return render(request, 'presail/prodject-presail-all.html',{'press':press , 'users':use ,'prod':prod })

    return render(request, 'presail/prodject-presail-all.html',{'press':press , 'users':use ,'prod':prod })

@login_required(login_url='/lg/')
def preseilmainmy(request): 
    use = User.objects.all()
    prod = ProductProd.objects.all() 
    press = PresProjNew.objects.exclude(status='Отказ').exclude(status='Завершен').filter(rpproecta=request.user.first_name)

    if request.method == 'POST':
        rp = request.POST.get('rp')
        products = request.POST.get('product')
        polzvt = request.POST.get('polzvt') 
        status = request.POST.get('status')
        #sum1 = request.POST.get('sum1')
        #sum2 = request.POST.get('sum2')
        #kanal = request.POST.get('kanal') 
        if polzvt !='-' and status != '-' and rp != '-' and products != '-':
            press = PresProjNew.objects.filter(rpproecta=rp).filter(status=status).filter(polzvt=polzvt).filter(products=products)

        elif polzvt =='-' and status == '-' and rp == '-' and products != '-':
            press = PresProjNew.objects.filter(products=products)
        elif polzvt =='-' and status == '-' and rp != '-' and products == '-':
            press = PresProjNew.objects.filter(rpproecta=rp)
        elif polzvt =='-' and status != '-' and rp == '-' and products == '-':
            press = PresProjNew.objects.filter(status=status)
        elif polzvt !='-' and status == '-' and rp == '-' and products == '-':
            press = PresProjNew.objects.filter(polzvt=polzvt)

        elif polzvt =='-' and status != '-' and rp != '-' and products != '-':
            press = PresProjNew.objects.filter(rpproecta=rp).filter(status=status).filter(products=products)
        elif polzvt !='-' and status == '-' and rp != '-' and products != '-':
            press = PresProjNew.objects.filter(rpproecta=rp).filter(polzvt=polzvt).filter(products=products)
        elif polzvt !='-' and status != '-' and rp == '-' and products != '-':
            press = PresProjNew.objects.filter(status=status).filter(polzvt=polzvt).filter(products=products)
        elif polzvt !='-' and status != '-' and rp != '-' and products == '-':
            press = PresProjNew.objects.filter(rpproecta=rp).filter(status=status).filter(polzvt=polzvt)

        elif polzvt =='-' and status == '-' and rp != '-' and products != '-':
            press = PresProjNew.objects.filter(rpproecta=rp).filter(products=products)
        elif polzvt !='-' and status == '-' and rp == '-' and products != '-':
            press = PresProjNew.objects.filter(polzvt=polzvt).filter(products=products)
        elif polzvt !='-' and status != '-' and rp == '-' and products == '-':
            press = PresProjNew.objects.filter(status=status).filter(polzvt=polzvt)
        elif polzvt =='-' and status != '-' and rp != '-' and products == '-':
            press = PresProjNew.objects.filter(rpproecta=rp).filter(status=status)

        elif polzvt =='-' and status != '-' and rp == '-' and products != '-':
            press = PresProjNew.objects.filter(status=status).filter(products=products)
        elif polzvt !='-' and status == '-' and rp != '-' and products == '-':
            press = PresProjNew.objects.filter(rpproecta=rp).filter(polzvt=polzvt)
        elif polzvt =='-' and status != '-' and rp == '-' and products != '-':
            press = PresProjNew.objects.filter(status=status).filter(products=products)
        elif polzvt !='-' and status != '-' and rp == '-' and products == '-':
            press = PresProjNew.objects.filter(status=status).filter(polzvt=polzvt)


        else:
            press = PresProjNew.objects.all()


        #press = PresProjNew.objects.filter(rpproecta=rp).filter(status=status)
        return render(request, 'presail/prodject-presail-all.html',{'press':press , 'users':use ,'prod':prod })

    return render(request, 'presail/prodject-presail-all.html',{'press':press , 'users':use ,  'prod':prod})

@login_required(login_url='/lg/')
def preseilnew(request):
    use = User.objects.all()
    comp = Compani.objects.all()

    if request.method == 'POST':
        press = PresProjNew()
        press.title = request.POST.get('title') 
        press.kanal = request.POST.get('kanal') 
        press.summa = request.POST.get('prisezatrat')
        press.kontrok = request.POST.get('kontrok')
        press.polzvt = request.POST.get('polzvt')
        press.status = request.POST.get('status')
        press.rpproecta = request.POST.get('rpproecta')
        press.rucgrup = "pres"
        press.activedog = "Системный"
        press.save()

        st = StadiiProdaj()
        st.title =request.POST.get('title') 
        st.priailnnew = press
        st.save()
        return redirect('preseil:presail') 
    return render(request, 'presail/prodject-presail-new.html',{'users':use, "comp":comp})

@login_required(login_url='/lg/')
def preseilmain(request, pk):
    press =  PresProjNew.objects.get(id=pk)
    stadi =  StadiiProdaj.objects.get(priailnnew=press)
    koment = KomentForPresail.objects.filter(priailnnew=press)
    comp = Compani.objects.all()
    use = User.objects.all()
    compan = Compani.objects.filter(id=press.compani).first()
    prod = ProductProd.objects.all() 
    cont = Cotrudniri.objects.filter(projects=press).filter(tip='sotrudnic').exclude(statusof='Уволен')
    contac = Cotrudniri.objects.exclude(projects=press).filter(tip='sotrudnic').exclude(statusof='Уволен')
    #piseof = PriseofmyWok.objects.filter(projects=press)
    #komadamodel = list(PriseofmyWok.objects.filter(projects=press).values_list('otch_id', flat=True).distinct())
    
    komadamodel = OtchetforMonf.objects.all()[:6]

    if request.method == 'POST':
        tip = request.POST.get('tip')
        if tip == "stadii":
            status = request.POST.getlist('status')
            textar = request.POST.getlist('textsname')
            stadi.znacomstvostatus = status[0]
            stadi.znacomstvo = textar[0]

serverrp/preseil/templates/presail/prodject-presail-all.html
{% extends 'index.html' %}

<!-- титул  -->
{% block page_title %}
<title> Пресейл </title>
{% endblock %}

{% load static %}
{% load pres %}
<!-- Стили -->
{% block page_styles %}


{% endblock %}

<!-- Слайдер -->
{% block page_slader %}



{% endblock %}

{% block page_contecst %}

<div class="box">
        <div class="box-header">
            <h4 class="box-title">Пресейл</h4>
            <div class="box-controls pull-right">
              <div class="lookup lookup-circle lookup-right">
                <input type="text" name="s">
              </div>
            </div>
      </div>
      <!-- /.box-header -->
      <div class="box-body ">
        <div class="row">
          <div class="col-xl-12 col-12">	
            <div class="clearfix">
              <a href="{% url 'preseil:presailall' %}" class="btn btn-secondary mb-5">  Мои Пресейлы</a>
              
              {% if user.is_staff or user.username == "stepanova"  or  user.username == "tselikov" %}	  
              <a href="{% url 'preseil:presail' %}" class="btn btn-secondary mb-5">  Все Пресейлы</a>
              {% endif %}	
              <a href="{% url 'preseil:presailnew' %}" class="btn btn-secondary mb-5">  Добавить </a>
              <a href="{% url 'preseil:presailotchet' %}" class="btn btn-secondary mb-5">  Отчет </a>

              <button type="button" class="btn btn-outline-secondary mb-5 "  alt="default" data-toggle="modal" data-target="#filter">Фильтр</button>
              <!---->					
            </div>
          </div>
        </div>


      <div class="row">
          <div class="col-xl-12 col-12" >
          <div class="table-responsive">
            <table id="example5" class="table table-bordered table-striped" style="width:100%">
             <thead>
              <tr>
                <th>№</th>
                <th width='20%' >Проект</th>
                <th> Менеджер </th>
                <th > Канал </th>
                <th> Продукт </th>
                <th>Сумма </th>
                <th>Статус </th>
                <th>Вероятность</th>
                <th>Процент реализации  </th>
                <th>Последнее обновление </th>
              </tr>
            </thead>
            <tbody> 
              {% for itm in press %}
               
              <tr>
                <td> {{ forloop.counter }}</td>
                <td><a href="{% url 'preseil:preselproj' pk=itm.id %}">{{ itm.title }}</a></td>
                <td> {{ itm.rpproecta }} </td>
                <td> {{ itm.kanal }}</td>
                <td> {% for u in itm.products.all %}  {{ u.title }} {% empty %} -  {% endfor %}</td>
                <td> {{ itm.summa }}</td>
                <td> {{ itm.status }} </td>
                <td> {{ itm.veroytnost }} </td>
                <td> {{ itm.id|proxxx }} % </td>
                <td> {{ itm.id|otchetpresdata }} </td>
              </tr>
              
              {% endfor %}
              </tbody>
            </table>
          </div>

          </div>
      </div>
      </div>
      <!-- /.box-body -->
  </div>

  <div class="col-lg-12 col-12">
    <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" id ='filter' aria-hidden="true" style="display: none;">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <form action="" method="post">
          {% csrf_token %} 
        <div class="modal-header">
          <h4 class="modal-title" id="myLargeModalLabel"> Фильтр  </h4>
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        </div>
        
        <div class="modal-body">
          <div class="row">
            <div class="col-6" >
            <div class="form-group">
            <label> Менеджер</label>
            <select class="form-control" name="rp" >
              <option value="-">-</option> 
              {% for us in users %}
              <option value="{{ us.first_name }}">{{ us.first_name }}</option>
              {% endfor %}  
            </select>
            </div>
            </div>
            
            <div class="col-6" >
              <div class="form-group">
              <label> Продукт</label>
              <select class="form-control" name="product" >
                <option value="-">-</option> 
                {% for sd in prod %}
                <option value="{{ sd.id }}">{{ sd.title }}</option>
                {% endfor %}
              </select>
            </div>
            </div>
            
              <div class="col-6" >
                <div class="form-group">
                <label> Статус</label>
                <select class="form-control" name="status">
                  <option value="-">-</option> 
                  <option value="Активный">Активный</option>
                  <option value="На паузе">На паузе</option>
                  <option value="Отказ">Отказ</option>
                  <option value="Завершен">Завершен</option>
                </select>
                </div>
              </div>
              <div class="col-6" >
                <div class="form-group">
                <label> Группа</label>
                <select class="form-control" name="polzvt">
                  <option value="-">-</option> 
                  <option value="Первичный">Первичный</option>
                  <option value="Пользователь">Пользователь</option>
                </select>
                </div>
              </div>
          </div>
          <!--  
          <div class="row">
            <div class="col-6" >
              <div class="form-group mb-0">
                <label class="control-label">Сумма с</label>
                <input type="text" name='sum1' class="form-control" value="0">
              </div>
            </div>
            <div class="col-6" >
              <div class="form-group mb-0">
                <label class="control-label">Сумма до</label>
                <input type="text" name='sum2' class="form-control" value="10000000">
              </div>
            </div>
          </div>    
          -->
          <input type="submit" value="Поиск" class="btn btn-success btn-block ">
     
        </div>
        
      </form>
      </div>
      <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
    </div>
    </div>   


{% endblock %}



{% block page_staticjsandcss %}



<script src="{% static "projects/assets/vendor_components/datatable/datatables.min.js"%}"></script>


<script>


  //[Data Table Javascript]


$(function () {
    "use strict";
	//--------Individual column searching
	
    // Setup - add a text input to each footer cell
    $('#example5 tfoot th').each( function () {
        var title = $(this).text();
        $(this).html( '<input type="text" placeholder '+title+'" />' );
    } );
 
    // DataTable
    var table = $('#example5').DataTable(
      {
        'searching'  : true,
        language: {
          
          "url": "dataTables.russian.lang" ,
          "processing": "Подождите...",
          "search": "Поиск:",
          "lengthMenu": "Показать _MENU_ ",
          "info": "Записи с _START_ до _END_ из _TOTAL_ записей",
          "infoEmpty": "Записи с 0 до 0 из 0 записей",
          "infoFiltered": "(отфильтровано из _MAX_ записей)",
          "infoPostFix": "",
          "loadingRecords": "Загрузка записей...",
          "zeroRecords": "Записи отсутствуют.",
          "emptyTable": "В таблице отсутствуют данные",
          "paginate": {
            "first": "Первая",
            "previous": "Предыдущая",
            "next": "Следующая",
            "last": "Последняя"
          },
          "aria": {
            "sortAscending": ": активировать для сортировки столбца по возрастанию",
            "sortDescending": ": активировать для сортировки столбца по убыванию"
          }
      }
      }
    );
 
    // Apply the search
    table.columns().every( function () {
        var that = this;
 
        $( 'input', this.footer() ).on( 'keyup change', function () {
            if ( that.search() !== this.value ) {
                that
                    .search( this.value )
                    .draw();
            }
        } );
    } );
	

  }); // End of use strict
</script>

{% endblock %}

serverrp/preseil/templates/presail/prodject-presail-otch.html
{% extends 'index.html' %}

<!-- титул  -->
{% block page_title %}
<title> Пресейл </title>
{% endblock %}


{% load static %}
{% load pres %}
<!-- Стили -->
{% block page_styles %}

<style>

  #bly {
    width: 12px;
    height: 12px;
    background: #5A8DEE;
  }
  #green {
    width: 12px;
    height: 12px;
    background: #39DA8A;
  }
  
  </style>
    
{% endblock %}

<!-- Слайдер -->
{% block page_slader %}



{% endblock %}

{% block page_contecst %}

<div class="box">
        <div class="box-header">
            <h4 class="box-title">Пресейл</h4>
            <div class="box-controls pull-right">
              <div class="lookup lookup-circle lookup-right">
                <input type="text" name="s">
              </div>
            </div>
      </div>
      <!-- /.box-header -->
      <div class="box-body ">
        <div class="row">	
          <div class="col-12">
          <div class="box">
              <div class="box-body">
                <div class="clearfix">
                  <button type="button" class="btn btn-purple mb-5">Знакомство <br> {{ in|colof:'A' }} </button>
                  <button type="button" class="btn btn-primary mb-5">Экспресс обследование <br> {{ in|colof:'B' }}</button>
                  <button type="button" class="btn btn-cyan mb-5">Согласование КП  <br> {{ in|colof:'C' }}</button>
                  <button type="button" class="btn btn-info mb-5">Подготовка документации <br> {{ in|colof:'D' }}</button>
                  <button type="button" class="btn btn-default mb-5">Конкурсные процедуры <br> {{ in|colof:'E' }}</button>
                  <button type="button"  class="btn btn-outline btn-warning mb-5">Итог: <br> {{ in|colof:'J' }}</button>
                
                </div>
              </div>
              <!-- /.box-body -->
            </div>
          </div>

          <div class="col-lg-6 col-12">
            <div class="box">
              <div class="box-header">
                <h4 class="box-title">Количество пресейлов по менеджерам</h4>
              </div>
              <div class="box-body text-center">
                <canvas id="chartStacked1" height="150"></canvas>
              </div>
              <div class="box-body">
                <table >
                  <tr>
                    <td > <div id="bly"></div> </td>  <td>&#160; На паузе &#160;&#160;</td> <td> <div id="green"></div></td> <td> &#160; Активный  </td>
                  </tr>
                </table>
              </div>
              <!-- /.box-body -->
            </div>
            <!-- /.box -->			
          </div>  
      
          <div class="col-lg-6 col-12">
            <div class="box">
              <div class="box-header">
                <h4 class="box-title">Количество пресейлов по продуктам</h4>
              </div>
              <div class="box-body text-center">
                <canvas id="chartStacked2" height="150"></canvas>
              </div>
              <!-- /.box-body -->
            </div>
            <!-- /.box -->			
          </div> 
      
          <div class="col-lg-6 col-12">
          <div class="box">
            <div class="box-header">
              <h4 class="box-title">По статусам</h4>
            </div>

            <div class="box-body chart-responsive">
                <div class="chart" id="morrisDonut2" style="height: 300px;"></div>
              </div>
          </div>
       </div>
       <div class="col-lg-6 col-12">
        <div class="box">
          <div class="box-header">
            <h4 class="box-title">По источникам привлечения</h4>
          </div>

          <div class="box-body chart-responsive">
              <div class="chart" id="morrisDonut3" style="height: 300px;"></div>
            </div>
        </div>
     </div>
     <div class="col-12">
      <div class="box">
        <div class="box-header">
          <h4 class="box-title">Пресейлы</h4>
        </div>
        <div class="box-body">
          <div class="table-responsive">
            <table id="example5" class="table table-bordered table-striped" style="width:100%">
              <thead>
              <tr>
                <th>№</th>
                <th width='20%' >Проект</th>
                <th width='5%'> РП</th>
                <th width='60%'>Статус </th>
                <th>Продукт </th>
                <th>Сумма </th>
                <th>Контрактация </th>
              </tr>
              </thead>
              <tbody> 
              {% for itm in press %}
              <tr>
                <td> {{ forloop.counter }}</td>
                <td><a href="{% url 'preseil:preselproj' pk=itm.id %}">{{ itm.title }}</a> </td>
                <td>{{ itm.menedjer.first_name }} </td>
                <td> {{  itm.id|otchetpres  }}
                </td>
                <td> {% for u in itm.products.all %}  {{ u.title }} {% empty %} -  {% endfor %}</td>
                <td> {{ itm.summa }}</td>
                <td> {{ itm.kontrok }} </td>
                
              </tr>
              
              {% endfor %}
            </tbody>
            </table>
          </div>



          </div>
      </div>
   </div>

        
        </div>
      </div>
      <!-- /.box-body -->
  </div>


{% endblock %}


{% block page_staticjsandcss %}

<script src="{% static "projects/assets/vendor_components/jquery-knob/js/jquery.knob.js"%}"></script>
	
<!-- Sparkline -->
<script src="{% static "projects/assets/vendor_components/jquery-sparkline/dist/jquery.sparkline.min.js"%}"></script>


<!-- Materiel Admin for Chart purposes -->

<script src="{% static "projects/assets/vendor_components/chart.js-master/Chart.bundle.js"%}"></script>
<script src="{% static "projects/assets/vendor_components/chart.js-master/utils.js"%}"></script>

<!-- SlimScroll -->
<script src="{% static "projects/assets/vendor_components/jquery-slimscroll/jquery.slimscroll.js"%}"></script>


<!-- Morris.js charts -->
<script src="{% static "projects/assets/vendor_components/raphael/raphael.min.js"%}"></script>
<script src="{% static "projects/assets/vendor_components/morris.js/morris.min.js"%}"></script>


<!-- Materiel Admin for inline Chart purposes -->
<script src="{% static "projects/js/pages/widget-inline-charts.js"%}"></script>

<script src="{% static "projects/assets/vendor_components/datatable/datatables.min.js"%}"></script>
	
<script src="{% static "projects/js/pages/data-table.js"%}"></script>
<script src="{% static "projects/js/pages/project-table.js"%}"></script>


<script>

$( document ).ready(function() {
    "use strict";
	
  var ctx7 = document.getElementById('chartStacked1');
  new Chart(ctx7, {
    type: 'bar',
    data: {
      labels: {{fio|safe}},
      datasets: [{
        data: {{fio|active:'A'}},
        backgroundColor: '#39DA8A',
        borderWidth: 1,
        fill: true
      },{
        data: {{fio|active:'B'}},
        backgroundColor: '#5A8DEE',
        borderWidth: 1,
        fill: true
      }]
    },
    options: {
      legend: {
        display: false,
          labels: {
            display: false
          }
      },
      scales: {
        yAxes: [{
          stacked: true
        }],
        xAxes: [{
          stacked: true
        }]
      }
    }
  });

  var ctx8 = document.getElementById('chartStacked2');
  new Chart(ctx8, {
    type: 'horizontalBar',
    data: {
      labels: [{% for u in prod.all %}  '{{ u.title }}',  {% endfor %}],
      datasets: [{
        data: [{% for u in prod.all %}  {{ u.title|product }},  {% endfor %}],
        backgroundColor: '#5A8DEE',
        borderWidth: 1,
        fill: true
      }]
    },
    options: {
      legend: {
        display: false,
          labels: {
            display: false
          }
      },
      scales: {
        yAxes: [{
          stacked: true
        }],
        xAxes: [{
          stacked: true
        }]
      }
    }
  });
});

</script>

<script>
  
  $(function(){
  'use strict';
  new Morris.Donut({
    element: 'morrisDonut2',
    data: [
    {label: "Активный", value: {{fio|statusof:'A'}} },
    {label: "На паузе", value: {{fio|statusof:'B'}} },
      
    ],
    colors: ['#39DA8A','#5A8DEE','#FDAC41','#FF5B5C'],
    resize: true
  });

  new Morris.Donut({
    element: 'morrisDonut3',
    data:[ 
      {{  fio|privleth|safe }}
     ],
    colors: ['#39DA8A','#5A8DEE','#FDAC41','#FF5B5C'],
    resize: true
  });
});  
  
</script>



{% endblock %}